### ISSUE TITLE
Occasional error with TitanIndexTest.testIndexUpdatesWithoutReindex

### ISSUE THREAD

**Issue by BrynCooke** [thinkaurelius/titan#1005] opened 2015-04-13 15:45 UTC
Occasionally the test fails:

```
Running com.thinkaurelius.titan.diskstorage.lucene.BerkeleyLuceneTest
Index [theIndex] job status: com.thinkaurelius.titan.diskstorage.keycolumnvalue.scan.StandardScannerExecutor@13bdf540
Index [theIndex] job status: com.thinkaurelius.titan.diskstorage.keycolumnvalue.scan.StandardScannerExecutor@13bdf540
Tests run: 20, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 147.656 sec <<< FAILURE! - in com.thinkaurelius.titan.diskstorage.lucene.BerkeleyLuceneTest
testIndexUpdatesWithoutReindex(com.thinkaurelius.titan.diskstorage.lucene.BerkeleyLuceneTest)  Time elapsed: 25.566 sec  <<< ERROR!
com.thinkaurelius.titan.core.TitanException: Could not execute operation due to backend exception
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:44)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:428)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.edgeStoreQuery(BackendTransaction.java:253)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.edgeQuery(StandardTitanGraph.java:415)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph$1.retrieveSchemaRelations(StandardTitanGraph.java:368)
    at com.thinkaurelius.titan.graphdb.database.cache.StandardSchemaCache.getSchemaRelations(StandardSchemaCache.java:156)
    at com.thinkaurelius.titan.graphdb.types.vertices.TitanSchemaVertex.getRelated(TitanSchemaVertex.java:99)
    at com.thinkaurelius.titan.graphdb.types.indextype.MixedIndexTypeWrapper.getFieldKeys(MixedIndexTypeWrapper.java:36)
    at com.thinkaurelius.titan.graphdb.types.indextype.MixedIndexTypeWrapper.getFieldKeys(MixedIndexTypeWrapper.java:12)
    at com.thinkaurelius.titan.graphdb.database.management.TitanGraphIndexWrapper.getFieldKeys(TitanGraphIndexWrapper.java:48)
    at com.thinkaurelius.titan.core.util.ManagementUtil.awaitIndexUpdate(ManagementUtil.java:67)
    at com.thinkaurelius.titan.core.util.ManagementUtil.awaitGraphIndexUpdate(ManagementUtil.java:40)
    at com.thinkaurelius.titan.graphdb.TitanIndexTest.testIndexUpdatesWithoutReindex(TitanIndexTest.java:1171)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runners.Suite.runChild(Suite.java:127)
    at org.junit.runners.Suite.runChild(Suite.java:26)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createReqestAndRun(JUnitCoreWrapper.java:139)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:111)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:84)
    at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:135)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.thinkaurelius.titan.diskstorage.PermanentBackendException: Permanent failure in storage backend
    at com.thinkaurelius.titan.diskstorage.berkeleyje.BerkeleyJEKeyValueStore.getSlice(BerkeleyJEKeyValueStore.java:166)
    at com.thinkaurelius.titan.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreAdapter.getSlice(OrderedKeyValueStoreAdapter.java:56)
    at com.thinkaurelius.titan.diskstorage.keycolumnvalue.cache.KCVSCache.getSliceNoCache(KCVSCache.java:63)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction$1.call(BackendTransaction.java:257)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction$1.call(BackendTransaction.java:253)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:56)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:42)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:428)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.edgeStoreQuery(BackendTransaction.java:253)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.edgeQuery(StandardTitanGraph.java:415)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph$1.retrieveSchemaRelations(StandardTitanGraph.java:368)
    at com.thinkaurelius.titan.graphdb.database.cache.StandardSchemaCache.getSchemaRelations(StandardSchemaCache.java:156)
    at com.thinkaurelius.titan.graphdb.types.vertices.TitanSchemaVertex.getRelated(TitanSchemaVertex.java:99)
    at com.thinkaurelius.titan.graphdb.types.indextype.MixedIndexTypeWrapper.getFieldKeys(MixedIndexTypeWrapper.java:36)
    at com.thinkaurelius.titan.graphdb.types.indextype.MixedIndexTypeWrapper.getFieldKeys(MixedIndexTypeWrapper.java:12)
    at com.thinkaurelius.titan.graphdb.database.management.TitanGraphIndexWrapper.getFieldKeys(TitanGraphIndexWrapper.java:48)
    at com.thinkaurelius.titan.core.util.ManagementUtil.awaitIndexUpdate(ManagementUtil.java:67)
    at com.thinkaurelius.titan.core.util.ManagementUtil.awaitGraphIndexUpdate(ManagementUtil.java:40)
    at com.thinkaurelius.titan.graphdb.TitanIndexTest.testIndexUpdatesWithoutReindex(TitanIndexTest.java:1171)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runners.Suite.runChild(Suite.java:127)
    at org.junit.runners.Suite.runChild(Suite.java:26)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createReqestAndRun(JUnitCoreWrapper.java:139)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:111)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:84)
    at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:135)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.sleepycat.je.LockTimeoutException: (JE 5.0.73) Lock expired. Locker 15288143 471_main_Txn: waited for lock on database=edgestore LockAddr:408551386 LSN=0x0/0x745d type=READ grant=WAIT_NEW timeoutMillis=500 startTime=1428928019667 endTime=1428928020167
Owners: [<LockInfo locker="585637516 466_pool-132-thread-1_Txn" type="WRITE"/>]
Waiters: []

    at com.sleepycat.je.txn.LockManager.newLockTimeoutException(LockManager.java:664)
    at com.sleepycat.je.txn.LockManager.makeTimeoutMsgInternal(LockManager.java:623)
    at com.sleepycat.je.txn.SyncedLockManager.makeTimeoutMsg(SyncedLockManager.java:97)
    at com.sleepycat.je.txn.LockManager.lockInternal(LockManager.java:390)
    at com.sleepycat.je.txn.LockManager.lock(LockManager.java:276)
    at com.sleepycat.je.txn.Txn.lockInternal(Txn.java:498)
    at com.sleepycat.je.txn.Locker.lock(Locker.java:443)
    at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:2621)
    at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:2422)
    at com.sleepycat.je.dbi.CursorImpl.fetchCurrent(CursorImpl.java:2253)
    at com.sleepycat.je.dbi.CursorImpl.getCurrentAlreadyLatched(CursorImpl.java:1466)
    at com.sleepycat.je.dbi.CursorImpl.getNext(CursorImpl.java:1593)
    at com.sleepycat.je.Cursor.searchInternal(Cursor.java:2742)
    at com.sleepycat.je.Cursor.searchAllowPhantoms(Cursor.java:2576)
    at com.sleepycat.je.Cursor.searchNoDups(Cursor.java:2430)
    at com.sleepycat.je.Cursor.search(Cursor.java:2397)
    at com.sleepycat.je.Cursor.getSearchKeyRange(Cursor.java:1727)
    at com.thinkaurelius.titan.diskstorage.berkeleyje.BerkeleyJEKeyValueStore.getSlice(BerkeleyJEKeyValueStore.java:123)
    at com.thinkaurelius.titan.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreAdapter.getSlice(OrderedKeyValueStoreAdapter.java:56)
    at com.thinkaurelius.titan.diskstorage.keycolumnvalue.cache.KCVSCache.getSliceNoCache(KCVSCache.java:63)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction$1.call(BackendTransaction.java:257)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction$1.call(BackendTransaction.java:253)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:56)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:42)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:428)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.edgeStoreQuery(BackendTransaction.java:253)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.edgeQuery(StandardTitanGraph.java:415)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph$1.retrieveSchemaRelations(StandardTitanGraph.java:368)
    at com.thinkaurelius.titan.graphdb.database.cache.StandardSchemaCache.getSchemaRelations(StandardSchemaCache.java:156)
    at com.thinkaurelius.titan.graphdb.types.vertices.TitanSchemaVertex.getRelated(TitanSchemaVertex.java:99)
    at com.thinkaurelius.titan.graphdb.types.indextype.MixedIndexTypeWrapper.getFieldKeys(MixedIndexTypeWrapper.java:36)
    at com.thinkaurelius.titan.graphdb.types.indextype.MixedIndexTypeWrapper.getFieldKeys(MixedIndexTypeWrapper.java:12)
    at com.thinkaurelius.titan.graphdb.database.management.TitanGraphIndexWrapper.getFieldKeys(TitanGraphIndexWrapper.java:48)
    at com.thinkaurelius.titan.core.util.ManagementUtil.awaitIndexUpdate(ManagementUtil.java:67)
    at com.thinkaurelius.titan.core.util.ManagementUtil.awaitGraphIndexUpdate(ManagementUtil.java:40)
    at com.thinkaurelius.titan.graphdb.TitanIndexTest.testIndexUpdatesWithoutReindex(TitanIndexTest.java:1171)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runners.Suite.runChild(Suite.java:127)
    at org.junit.runners.Suite.runChild(Suite.java:26)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createReqestAndRun(JUnitCoreWrapper.java:139)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:111)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:84)
    at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:135)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by dalaro** [comment] 2015-04-15 04:44
Has this only appeared so far on BDB?

**Comment by BrynCooke** [comment] 2015-04-15 08:47
Not sure I do almost all my testing against BDB as it it most convenient, I'll let you know if I sport it happening against any of the other back ends.

**Comment by dalaro** [comment] 2015-04-23 04:59
In general, it's not too hard to imagine a BDB read from `ManagementUtil.awaitGraphIndexUpdate` interfering with some other concurrent operation.  But I don't understand how that could happen in this test.  I thought the log from a failed execution might help, but 50 executions of `BerkeleyElasticsearchTest.testIndexUpdatesWithoutReindex` in a loop running in the background wasn't enough to generate a failure.

**Comment by dalaro** [comment] 2015-08-27 22:12
I'm closing this since I haven't been able to reproduce it and I'm out of ideas.  Please reopen if we get a new lead.

**Closed as completed by dalaro** 2015-08-27 22:12 UTC
Labels: bug
