### ISSUE TITLE
g.V.count() returning only half the vertices.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#227] opened 2013-04-16 01:15 UTC
I don't have a good test case for this, but will simply provide my observation as it may trigger and obvious realization.

I bulk loaded a graph into Titan using Faunus.

Titan:

``` groovy
gremlin> g.V.count()
==>830125
```

Faunus:

``` groovy
gremlin> g.V.count()
==>1660250
```

This is exactly half the number of vertices. ? ... Titan's g.V iterator is not returning all the data. Why exactly half? -- seems a little to perfect. Note, I'm using Titan 0.3.0.

**Comment by mbroecheler** [comment] 2013-04-17 04:04
Is there some obvious symmetry in the data? Like an equal number of in and
out edges?

On Mon, Apr 15, 2013 at 6:15 PM, Marko A. Rodriguez <
notifications@github.com> wrote:

> I don't have a good test case for this, but will simply provide my
> observation as it may trigger and obvious realization.
> 
> I bulk loaded a graph into Titan using Faunus.
> 
> Titan:
> 
> gremlin> g.V.count()==>830125
> 
> Faunus:
> 
> gremlin> g.V.count()==>1660250
> 
> This is exactly half the number of vertices. ? ... Titan's g.V iterator is
> not returning all the data. Why exactly half? -- seems a little to perfect.
> Note, I'm using Titan 0.3.0.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/227
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by xedin** [comment] 2013-04-23 17:46
Marko, is there any way to try to import the same dataset and test?

**Comment by okram** [comment] 2013-04-23 18:07
Unless there is an obvious realization, please ignore this ticket until I
can demonstrate a test case to validates the odd behavior.

**Comment by anvie** [comment] 2013-04-25 08:36
Hi all, is this problem related?:

When iterating from `outE` I got the right result:

``` groovy
gremlin> g.v(92).outE("own")
==>e[9yV-1u-2F0LaTPQN0][92-own->180]
==>e[9yR-1u-2F0LaTPQN0][92-own->184]
==>e[9yP-1u-2F0LaTPQN0][92-own->192]
==>e[9yN-1u-2F0LaTPQN0][92-own->204]
==>e[9yT-1u-2F0LaTPQN0][92-own->212]
==>e[9yZ-1u-2F0LaTPQN0][92-own->144]
==>e[9yX-1u-2F0LaTPQN0][92-own->152]
```

But when using `g.E` those edges never seen:

``` groovy
gremlin> g.E.has("label", "own")
==>e[9TX-k-2F0LaTPQN0][20-own->168]
==>e[9TV-k-2F0LaTPQN0][20-own->172]
==>e[9TT-k-2F0LaTPQN0][20-own->196]
==>e[9hr-o-2F0LaTPQN0][24-own->156]
```

**Comment by mbroecheler** [comment] 2013-04-25 17:03
This is strange. Do you have a dataset this can be reproduced on?

On Thu, Apr 25, 2013 at 1:36 AM, Robin Syihab notifications@github.comwrote:

> Hi all, is this problem related?:
> 
> When iterating from outE I got the right result:
> 
> gremlin> g.v(92).outE("own")==>e[9yV-1u-2F0LaTPQN0][92-own->180]==>e[9yR-1u-2F0LaTPQN0][92-own->184]==>e[9yP-1u-2F0LaTPQN0][92-own->192]==>e[9yN-1u-2F0LaTPQN0][92-own->204]==>e[9yT-1u-2F0LaTPQN0][92-own->212]==>e[9yZ-1u-2F0LaTPQN0][92-own->144]==>e[9yX-1u-2F0LaTPQN0][92-own->152]
> 
> But when using g.E those edges never seen:
> 
> gremlin> g.E.has("label", "own")==>e[9TX-k-2F0LaTPQN0][20-own->168]==>e[9TV-k-2F0LaTPQN0][20-own->172]==>e[9TT-k-2F0LaTPQN0][20-own->196]==>e[9hr-o-2F0LaTPQN0][24-own->156]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/227#issuecomment-16994711
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by anvie** [comment] 2013-04-25 17:56
@mbroecheler 
here is my cassandra data to reproduce this behavior: 
http://dmcd6hvaqrxz0.cloudfront.net/tmp/cassandra-data.tar.bz2
My environment:
Cassandra version:

```
INFO 00:33:08,494 Cassandra version: 1.2.3
INFO 00:33:08,494 Thrift API version: 19.35.0
INFO 00:33:08,494 CQL supported versions: 2.0.0,3.0.1 (default: 3.0.1)
```

Titan all 0.3.0 downloaded from http://s3.thinkaurelius.com/downloads/titan/titan-all-0.3.0.zip
Using cassandra local mode:

``` bash
$ cat cassandra.local 
storage.backend=cassandra
storage.hostname=127.0.0.1
```

My gremlin commands after pointing cassandra to my data:

```
         \,,,/
         (o o)
-----oOOo-(_)-oOOo-----
gremlin> g = TitanFactory.open("cassandra.local")
13/04/26 00:42:07 INFO impl.ConnectionPoolMBeanManager: Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=ClusterTitanConnectionPool,ServiceType=connectionpool
13/04/26 00:42:08 INFO impl.ConnectionPoolMBeanManager: Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=KeyspaceTitanConnectionPool,ServiceType=connectionpool
13/04/26 00:42:08 WARN idassigner.VertexIDAssigner: ID Partitioning is disabled which will likely cause uneven data distribution
==>titangraph[cassandra:127.0.0.1]
gremlin> g.v(92).outE("own")
==>e[9yV-1u-2F0LaTPQN0][92-own->180]
==>e[9yR-1u-2F0LaTPQN0][92-own->184]
==>e[9yP-1u-2F0LaTPQN0][92-own->192]
==>e[9yN-1u-2F0LaTPQN0][92-own->204]
==>e[9yT-1u-2F0LaTPQN0][92-own->212]
==>e[9yZ-1u-2F0LaTPQN0][92-own->144]
==>e[9yX-1u-2F0LaTPQN0][92-own->152]
gremlin> g.E.has("label","own")
==>e[9TX-k-2F0LaTPQN0][20-own->168]
==>e[9TV-k-2F0LaTPQN0][20-own->172]
==>e[9TT-k-2F0LaTPQN0][20-own->196]
==>e[9hr-o-2F0LaTPQN0][24-own->156]
```

**Comment by xedin** [comment] 2013-04-25 18:12
@anvie Thanks! I can reproduce the problem now, already started working on this.

**Comment by xedin** [comment] 2013-04-25 18:20
Ah, I know what the problem is - global operations are only supported on random partitioning (RandomPartitioner, Mumur3Partitioner), thrift and embedded does throw an exception but Astyanax has to way to query what partitioner is used in the system (and they only support RandomPartitioner). It's confusing and I will try to figure something out to actually notify users that if BOP is used g.E and g.V are not going to work in any of the clients. 

e.g. https://github.com/Netflix/astyanax/issues/126 people had similar problem with Astyanax and BOP

Edit: Astyanax has a way to query what partitioner is used but they just hardcode RandomPartitioner for getAllRows(...) query which gives incorrect results, I'm working on making that an error so it's at least less confusing.

**Comment by mbroecheler** [comment] 2013-05-02 18:27
@xedin : Can we close this?

**Comment by xedin** [comment] 2013-05-05 06:59
Error reporting is merged, closing.

**Closed as completed by xedin** 2013-05-05 06:59 UTC
Labels: question

**Comment by anvie** [comment] 2013-06-12 15:57
Hi @xedin, so do you have any idea howto rescue my data in my cassandra that using BOP to new cassandra with random partitioner? 
Now I'm trying to dump all existing data from cassandra and migrate to another cassandra with random partitioner, 
Direct access using gremlin (in Titan 0.3.1) I'm got error:
`This operation is only allowed when random partitioner (md5 or murmur3) is used`
and when using Faunus:

```
g.V.count                                                     
13/06/12 22:36:42 WARN mapreduce.FaunusCompiler: Using distribution reference to lib/faunus-0.3.1-job.jar
13/06/12 22:36:42 INFO mapreduce.FaunusCompiler: Compiled to 1 MapReduce job(s)
13/06/12 22:36:42 INFO mapreduce.FaunusCompiler: Executing job 1 out of 1: MapSequence[com.thinkaurelius.faunus.mapreduce.transform.VerticesMap.Map, com.thinkaurelius.faunus.mapreduce.util.CountMapReduce.Map, com.thinkaurelius.faunus.mapreduce.util.CountMapReduce.Reduce]
13/06/12 22:36:42 INFO mapreduce.FaunusCompiler: Job data location: output/job-0
13/06/12 22:36:42 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
13/06/12 22:36:43 WARN idassigner.VertexIDAssigner: ID Partitioning is disabled which will likely cause uneven data distribution
13/06/12 22:36:43 INFO mapred.JobClient: Cleaning up the staging area file:/tmp/hadoop-root/mapred/staging/root-309118976/.staging/job_local_0004
13/06/12 22:36:43 ERROR security.UserGroupInformation: PriviledgedActionException as:root cause:java.io.IOException: Could not get input splits
Could not get input splits
Display stack trace? [yN] y
```

Stack trace:

```
java.lang.RuntimeException: Could not get input splits
    at com.thinkaurelius.faunus.tinkerpop.gremlin.ResultHookClosure.call(ResultHookClosure.java:54)
    at groovy.lang.Closure.call(Closure.java:428)
    at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:231)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:64)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.codehaus.groovy.tools.shell.Groovysh.setLastResult(Groovysh.groovy:324)
    at org.codehaus.groovy.tools.shell.Groovysh.this$3$setLastResult(Groovysh.groovy)
    at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2416)
    at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3347)
    at org.codehaus.groovy.tools.shell.Shell.setProperty(Shell.groovy)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setGroovyObjectProperty(ScriptBytecodeAdapter.java:528)
    at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
    at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
    at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
    at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
    at com.thinkaurelius.faunus.tinkerpop.gremlin.Console.<init>(Console.java:54)
    at com.thinkaurelius.faunus.tinkerpop.gremlin.Console.<init>(Console.java:61)
    at com.thinkaurelius.faunus.tinkerpop.gremlin.Console.main(Console.java:66)
Caused by: java.io.IOException: Could not get input splits
    at org.apache.cassandra.hadoop.ColumnFamilyInputFormat.getSplits(ColumnFamilyInputFormat.java:169)
    at com.thinkaurelius.faunus.formats.titan.cassandra.TitanCassandraInputFormat.getSplits(TitanCassandraInputFormat.java:40)
    at org.apache.hadoop.mapred.JobClient.writeNewSplits(JobClient.java:1024)
    at org.apache.hadoop.mapred.JobClient.writeSplits(JobClient.java:1041)
    at org.apache.hadoop.mapred.JobClient.access$700(JobClient.java:179)
    at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:959)
    at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:912)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1149)
    at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:912)
    at org.apache.hadoop.mapreduce.Job.submit(Job.java:500)
    at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:530)
    at com.thinkaurelius.faunus.mapreduce.FaunusCompiler.run(FaunusCompiler.java:311)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:79)
    at com.thinkaurelius.faunus.FaunusPipeline.submit(FaunusPipeline.java:1075)
    at com.thinkaurelius.faunus.FaunusPipeline.submit(FaunusPipeline.java:1058)
    at com.thinkaurelius.faunus.tinkerpop.gremlin.ResultHookClosure.call(ResultHookClosure.java:38)
    ... 55 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NumberFormatException: Non-hex characters in Token(bytes[6bae317edaf25324fb66781d0b04afd1])
    at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
    at java.util.concurrent.FutureTask.get(FutureTask.java:83)
    at org.apache.cassandra.hadoop.ColumnFamilyInputFormat.getSplits(ColumnFamilyInputFormat.java:165)
    ... 73 more
Caused by: java.lang.NumberFormatException: Non-hex characters in Token(bytes[6bae317edaf25324fb66781d0b04afd1])
    at org.apache.cassandra.utils.Hex.hexToBytes(Hex.java:60)
    at org.apache.cassandra.dht.AbstractByteOrderedPartitioner$1.fromString(AbstractByteOrderedPartitioner.java:168)
    at org.apache.cassandra.hadoop.ColumnFamilyInputFormat$SplitCallable.call(ColumnFamilyInputFormat.java:219)
    at org.apache.cassandra.hadoop.ColumnFamilyInputFormat$SplitCallable.call(ColumnFamilyInputFormat.java:187)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
```

**Comment by anvie** [comment] 2013-06-12 16:42
Just walking around and found this: https://issues.apache.org/jira/browse/CASSANDRA-5566 
maybe related issue?
