### ISSUE TITLE
Can not instantiate BekereleyJSEStorageManager from bin/gremlin.sh (the developer root)

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#177] opened 2013-03-12 20:03 UTC
gremlin>
gremlin> conf = new BaseConfiguration()
==>org.apache.commons.configuration.BaseConfiguration@5f8581f3
gremlin> conf.setProperty('storage.directory','/tmp/jason-test2')
==>null
gremlin> conf.setProperty('storage.batch-loading','true')
==>null
gremlin> conf.setProperty('storage.backend','local')
==>null
gremlin> g = TitanFactory.open(conf)
Could not instantiate implementation: com.thinkaurelius.titan.diskstorage.berkeleyje.BerkeleyJEStoreManager
Display stack trace? [yN] y

**Comment by xedin** [comment] 2013-03-18 21:14
This is what exception says to me

Caused by: java.lang.IllegalArgumentException: Cannot open or write to directory: /tmp/jason-test2
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
    at com.thinkaurelius.titan.diskstorage.berkeleyje.BerkeleyJEStoreManager.<init>(BerkeleyJEStoreManager.java:53)
    ... 56 more

So it seems like BerkleyJE just can't create directories on it's own. Can you please check what exception does it return to you?

**Comment by okram** [comment] 2013-03-18 21:22
Caused by: java.lang.IllegalArgumentException: Cannot open or write to directory: /tmp/jason-test2
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
    at com.thinkaurelius.titan.diskstorage.berkeleyje.BerkeleyJEStoreManager.<init>(BerkeleyJEStoreManager.java:53)
    ... 56 more

this did not use to be the case?

**Comment by xedin** [comment] 2013-03-18 21:53
Actually we can try to create a directory on startup if it doesn't exist, but it looks like it was always the case.

**Comment by okram** [comment] 2013-03-18 22:04
I don't think  this was always the case -- Matthias?

**Comment by xedin** [comment] 2013-03-18 22:05
It should have been because nothing is creating it and there is Precondition to check if it exists.

**Comment by xedin** [comment] 2013-03-18 22:21
Pull https://github.com/thinkaurelius/titan/pull/181 would create directory if it doesn't exist also does necessary checks.

**Comment by xedin** [comment] 2013-03-20 06:17
Merged, closing.

**Closed as completed by xedin** 2013-03-20 06:17 UTC
