### ISSUE TITLE
Titan 0.4.2 not able to connect to remote ElasticSearch 1.0.0

### ISSUE THREAD

**Issue by yammelvin** [thinkaurelius/titan#598] opened 2014-02-21 03:27 UTC
I saw under release note, Titan 0.4.2 is compatible with ElasticSearch 0.90.5,
and I have successfully connect to ElasticSearch 0.90.5 remotely.
However, when I tried to connect to ElasticSearch 1.0.0 remotely, it throws the following Exception:

```
0    [main] INFO  com.netflix.astyanax.connectionpool.impl.ConnectionPoolMBeanManager  - Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=ClusterTitanConnectionPool,ServiceType=connectionpool
8    [main] INFO  com.netflix.astyanax.connectionpool.impl.CountingConnectionPoolMonitor  - AddHost: 127.0.0.1
71   [main] INFO  com.netflix.astyanax.connectionpool.impl.ConnectionPoolMBeanManager  - Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=KeyspaceTitanConnectionPool,ServiceType=connectionpool
71   [main] INFO  com.netflix.astyanax.connectionpool.impl.CountingConnectionPoolMonitor  - AddHost: 127.0.0.1
150  [main] INFO  com.thinkaurelius.titan.diskstorage.Backend  - Configuring index [search] based on: 
 backend: elasticsearch
hostname: 127.0.0.1
client-only: true

213  [main] INFO  org.elasticsearch.plugins  - [Perun] loaded [], sites []
533  [main] INFO  com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex  - Configured remote host: 127.0.0.1 : 9300
601  [elasticsearch[Perun][transport_client_worker][T#1]{New I/O worker #1}] INFO  org.elasticsearch.client.transport  - [Perun] failed to get local cluster state for [#transport#-1][inet[/127.0.0.1:9300]], disconnecting...
org.elasticsearch.transport.RemoteTransportException: Failed to deserialize exception response from stream
Caused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize exception response from stream
    at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:168)
    at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:122)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.InvalidClassException: failed to read class descriptor
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1603)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1622)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1622)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1622)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
    at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:166)
    ... 23 more
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.ElasticsearchException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at org.elasticsearch.common.io.ThrowableObjectInputStream.loadClass(ThrowableObjectInputStream.java:93)
    at org.elasticsearch.common.io.ThrowableObjectInputStream.readClassDescriptor(ThrowableObjectInputStream.java:67)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1601)
    ... 34 more
606  [elasticsearch[Perun][transport_client_worker][T#1]{New I/O worker #1}] WARN  org.elasticsearch.transport.netty  - [Perun] Message not fully read (response) for [0] handler org.elasticsearch.client.transport.TransportClientNodesService$SniffNodesSampler$1$1@4a3993, error [true], resetting
Exception in thread "main" java.lang.IllegalArgumentException: Could not instantiate implementation: com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex
    at com.thinkaurelius.titan.diskstorage.Backend.instantiate(Backend.java:355)
    at com.thinkaurelius.titan.diskstorage.Backend.getImplementationClass(Backend.java:367)
    at com.thinkaurelius.titan.diskstorage.Backend.getIndexes(Backend.java:331)
    at com.thinkaurelius.titan.diskstorage.Backend.<init>(Backend.java:122)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1163)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:75)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:29)
    at com.tests.MainClass.testTitan(MainClass.java:20)
    at com.tests.MainClass.main(MainClass.java:12)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.thinkaurelius.titan.diskstorage.Backend.instantiate(Backend.java:344)
    ... 9 more
Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: No node available
    at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:205)
    at org.elasticsearch.client.transport.support.InternalTransportClusterAdminClient.execute(InternalTransportClusterAdminClient.java:85)
    at org.elasticsearch.client.support.AbstractClusterAdminClient.health(AbstractClusterAdminClient.java:87)
    at org.elasticsearch.action.admin.cluster.health.ClusterHealthRequestBuilder.doExecute(ClusterHealthRequestBuilder.java:98)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.<init>(ElasticSearchIndex.java:161)
    ... 14 more
```

**Comment by jascks** [comment] 2014-02-21 14:59
@yammelvin I was curious if you were going to open this again. :) This is a real problem though as ES 1.0.0 has breaking API changes and Titan 0.4.2 does not work with it.  Is this issue a duplicate of another?  Or is there a future version of Titan that is targeting ES 1.0.0.?

Thanks, Jeff

**Comment by yammelvin** [comment] 2014-02-21 17:02
@jascks I closed it because apparently this is a widely known issue. I was hoping to find some workaround / solution.

**Comment by jascks** [comment] 2014-02-21 17:09
@yammelvin That makes sense. It is not subtle failure. :)  I don't know if all ES users will be running to 1.0 right away, so maybe a separate search backend implementation for 1.0 vs. pre-1.0?  This is all still pretty new to me, so I'm sure the powers that be will handle it well. :)

**Comment by bflad** [comment] 2014-02-25 22:38
I'll :+1: integration with Elasticsearch 1.0, we're beginning to upgrade a couple clusters already.

**Comment by jascks** [comment] 2014-02-25 23:46
Great @bflad!  Thanks.

**Comment by Colin-Mac-Donald** [comment] 2014-02-26 12:11
Thanks for documenting this.  I wouldn't call it "widely known", since it took me a few hours of thrashing and swearing to figure out that I wasn't actually mis-using Titan and Elastic Search.

New developers will just grab the latest version of both Titan and Elastic Search and expect them to work.  Why wouldn't we, since the Titan wiki Elastic Search page doesn't list version compatibility or incompatibility.

**Comment by spmallette** [comment] 2014-02-26 12:54
version compatibility can be found here: 

https://github.com/thinkaurelius/titan/wiki/Version-Compatibility

Added a link to this page from ES wiki page.

**Comment by bflad** [comment] 2014-02-26 12:59
FWIW that page should read 0.90.3+, <1.0.0 for all mentions of ES 0.90.X.
The Java client strictly is not compatible between ES versions.

Brian Flad

**Comment by spmallette** [comment] 2014-02-26 13:04
true....added a bit more clarity.  thanks.

**Comment by boneill42** [comment] 2014-02-26 14:06
+1, I would love to see this addressed.  Elastic Search 1.0 has compelling new functionality that people are likely going to want to take advantage of.  (e.g. aggregations)  It would be great to see Titan work with the new version.  Should this be re-opened?

**Comment by jascks** [comment] 2014-02-26 15:25
+1 here too.  I doubt all Titan/ES users will be jumping off of < 1.0.0 though...  Does there need to be a titan-es-pre-1.0 implementation and a new titan-es moving forward?  I would like to think ES won't be making any breaking API changes until ES 2.x.

**Comment by FarzadT** [comment] 2014-03-06 15:34
Does this fix the issue?
https://github.com/thinkaurelius/titan/pull/605

**Comment by dalaro** [comment] 2014-04-14 18:33
#605 makes Titan 0.5 support ES 1.0, but it doesn't maintain backwards compatibility with 0.90.  Titan 0.4 can only get ES 1.0 support if it doesn't interfere with 0.90 compatibility, since that's what it shipped with, so we can't merge the change from #605 into the 0.4 branch (without additional compatibility work like @jascks hinted at).

**Comment by dalaro** [comment] 2014-05-02 18:32
Summary: Titan 0.5 supports ES 1.x ; Titan 0.4.2 supports ES 0.90.x.  Pull requests for ES 1 on Titan 0.4 or ES 0.90 on Titan 0.5 are welcome so long as they don't break existing ES version support.

**Closed as completed by dalaro** 2014-05-02 18:32 UTC
