### ISSUE TITLE
Update Titan documentation so same ElasticSearch issue doesn't reoccur.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#506] opened 2013-12-02 15:51 UTC
I am trying to run this example and I get the following errors:
Exception in thread "main" java.lang.IllegalArgumentException: Could not instantiate implementation: com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex
    at com.thinkaurelius.titan.diskstorage.Backend.instantiate(Backend.java:346)
    at com.thinkaurelius.titan.diskstorage.Backend.getImplementationClass(Backend.java:358)
    at com.thinkaurelius.titan.diskstorage.Backend.getIndexes(Backend.java:322)
    at com.thinkaurelius.titan.diskstorage.Backend.<init>(Backend.java:116)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1108)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:75)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
    at test_pcg.GraphOfTheGodsFactory.create(GraphOfTheGodsFactory.java:43)
    at test_pcg.Test.main(Test.java:7)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.thinkaurelius.titan.diskstorage.Backend.instantiate(Backend.java:335)
    ... 8 more
Caused by: java.lang.NoSuchFieldError: LUCENE_41
    at org.elasticsearch.Version.<clinit>(Version.java:118)
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.checkExpectedClientVersion(ElasticSearchIndex.java:559)
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.<init>(ElasticSearchIndex.java:98)
    ... 13 more

What is the problem?

**Comment by mbroecheler** [comment] 2013-12-19 01:20
Everything seems to be good on the documentation side. I think this has to do with downloading the wrong distribution or having conflicting versions of Lucene on the classpath. Hence, this is really a duplicate of #514 and related issues.

**Closed as completed by mbroecheler** 2013-12-19 01:20 UTC
Labels: bug, documentation

**Comment by munkyboy** [comment] 2014-04-17 21:22
I also ran into this error using Titan 0.4.2 and ElasticSearch 0.90.x. Specifically, my ElasticSearch server is in a Docker container running inside a virtualbox VM and my Titan app is on the outermost host layer. I had to turn off the `sniff` option in order to get it working.

**Comment by mbroecheler** [comment] 2014-04-19 00:48
@munkyboy You got the above exception because the sniff option was on?

**Comment by munkyboy** [comment] 2014-04-19 21:14
@mbroecheler yes. when I set sniff to false everything worked as expected.

**Comment by mbroecheler** [comment] 2014-04-21 22:13
@munkyboy thanks. Added a trouble shooting section to:
https://github.com/thinkaurelius/titan/wiki/Using-Elastic-Search

**Comment by kevinschumacher** [comment] 2015-01-12 22:50
This has been closed for a long time, but I just want +1 @munkyboy's solution --  I also had to set sniff to false when running Titan 0.4.4 (built from source, tag 0.4.4) in Rexster 2.4.0 when connecting to ElasticSearch 0.90.13 on another server.
