### ISSUE TITLE
Very poor performance on indexed of Titan 0.3.0 + "could not instantiate implementation: com.thinkaurelius.titan.diskstorage.lucene.LuceneIndex"

### ISSUE THREAD

**Issue by antonkulaga** [thinkaurelius/titan#215] opened 2013-04-07 02:18 UTC
I updated to the latest titan and got very poor performance on indexes (seems like the do not work at all).

Code that was executed in a matter of seconds on previous versions of Titan (stuff like this https://github.com/hudvin/genes-demo/tree/master/src/main/scala ) now takes many minutes on both Berkeley and Cassandra backends.

And when I add index backends explicitness to the config I get "could not instantiate implementation: com.thinkaurelius.titan.diskstorage.lucene.LuceneIndex" even when I have them all in sbt settings: (i.e.  "com.thinkaurelius.titan" % "titan-lucene" % "0.3.0")

**Comment by okram** [comment] 2013-04-07 14:20
I am noticing index speed issues with Titan 0.3.0 as well. Not as significant as stated above, but a good 1.5x slow down. The example below is with Titan/BerkeleyDB, but have noticed this originally with a Titan/Cassandra project.

Titan 0.3.0 (BerkeleyDB) -- ~8 seconds cold cache. ~2.5 seconds warm cache.
Titan 0.2.0 (BerkeleyDB) -- ~5 seconds cold cache. ~1.5 seconds warm cache.

``` groovy
g = TitanFactory.open('/tmp/test020') // test030 for Titan 0.3.0 

g.createKeyIndex('name',Vertex.class)
(0..100000).each {
  g.addVertex(it).setProperty('name', 'name: ' + it)
}; g.stopTransaction(SUCCESS);

t = System.currentTimeMillis()
(0..100000).each {
  g.V('name','name: ' + it).iterate()
}; System.currentTimeMillis() - t;
```

**Comment by mbroecheler** [comment] 2013-04-07 20:29
To clarify, is that with lucene as the index or native titan?

**Comment by okram** [comment] 2013-04-08 15:07
I am noticing that we are getting "linear scan" behavior on this type of index.

``` groovy
g.makeType().name('name').dataType(String.class).indexed("search", Vertex.class).indexed(Vertex.class).unique(Direction.OUT).makePropertyKey();
g.makeType().name('uri').dataType(String.class).indexed("search", Vertex.class).unique(Direction.BOTH).makePropertyKey();
```

Each addition is checking the name and uri for existence before adding the vertex. The load process (of only 3000 vertices) gets slower and slower before nearly coming to a halt (1 vertex every ~2 seconds).

**Comment by antonkulaga** [comment] 2013-04-08 16:24
It is a link to Titan 0.21 code. On Titan 0.21 it works fast but when converted (to Titan 0.30 taking into consideration upgrade instructions  it became very slow). Seems like indexes and uniqueness work very differently now=(

**Comment by mbroecheler** [comment] 2013-04-08 20:24
Two things:
1. _On Standard index performance in Titan 0.2.1 vs 0.3.0_: The fact that Titan 0.3 performs worse for the small benchmark that Marko put together is to be expected for two reasons: 1) Titan 0.3 has a query optimizer for index calls due to the extended indexing functionality. Hence, each index call incurs more overhead and 2) Titan 0.3 introduces index query caching. That means, results to index calls are indexed so that subsequent index calls can be answered from memory. That is particularly useful for external indices. In this particular example, caching incurs a high toll, because 1 million index calls are executed in one transaction without doing any index calls twice. Hence, the cache has no benefit in this example but adds a lot of memory overhead. I think 2) is the primary reason for the performance difference, but I will run some profiling to make sure. We could consider making index caching optional for performance reasons. That said, the performance difference is not _that_ big and the benchmark is definitely an edge case. Most transactions won't be making that many calls.
2. _On the poor performance of external indices_: Note a couple of things here:
   - _Always_ use standard indices for equality lookups, i.e. @indexed(Vertex.class)@ or @indexed(Edge.class)@ without specifying the name of the index. In that case, Titan will use the same kind of index it used in prior versions. There is no benefit in using Lucene or ElasticSearch for equality lookups - in fact, they will be MUCH slower.
   - The Lucene implementation is currently not performance optimized. Its purpose is mostly unit testing. Use ElasticSearch for performance oriented applications or deployments
   - I noticed that both, Lucene and ElasticSearch, exhibit worse performance when executing reads during high write loads. That might be a configuration thing. My understanding is, that for a read the current write state must be flushed in order to ensure that everything is queried and that such flushes incur high overheads. However, I am no expert on these systems.

**Comment by okram** [comment] 2013-04-17 16:08
Here is a new experiment.

"getOrCreate" with an index hit to a 'name' Titan specific index. (NOT ElasticSearch) using Titan 0.3.0/Cassandra 1.2.2. Note that this is all within a single transaction (no %-modulo g.commit()).

1000     vertices added  -- 2.763 ms per vertex (total time: 2.7 seconds)
10000   vertices added  -- 10.5567 ms per vertex (total time: 105.56 seconds -- 1.7 minutes)
20000  vertices added -- 18.7935 (total time: 375.87 seconds -- 6.26 minutes)

NOTE: In my professional/expert/esteemed opinion, this is extremely slow. Note that the experiment I did above in my previous commet was NOT a "getOrCreate," but just "create" w/ getting after all vertices had been committed. Therefore, I suspect there is something odd happening when the index is queried in mid-transaction.

The code for this experiment is here:

``` groovy
g = TitanFactory.open('bin/cassandra.local')
g.makeType().name('name').dataType(String.class).indexed(Vertex.class).unique(Direction.OUT).makePropertyKey()
g.commit()

ring = ['a','b','c','d','e','f','g','h','i','j'] // not important -- using this for another experiment later around ES and CONTAINS
totalTime = 0;
totalVertices = 100000; // this was changed on each run
(0..totalVertices).each{
  t = System.currentTimeMillis();
  name = 'person ' + it + ' ' + ring[it%ring.size()]
  if(g.V('name',name).hasNext()) {
    println name + ' already exists.'
  } else {
    v = g.addVertex();
    v.setProperty('name',name)
  }
  totalTime = totalTime + System.currentTimeMillis() - t;
}; null

println "Total time for inserting ${totalVertices} was ${totalTime}"
println "Average time per vertex was ${totalTime / totalVertices}"

g.commit();
```

**Comment by okram** [comment] 2013-04-17 20:10
More information. We are now doing this:

Insert 1000 vertices with "getOrCreate" behavior hitting a Titan native 'name' index. It starts to come to a crawl near 1000, then g.commit(). It speeds up significantly. As it approaches 2000, it comes a crawl. g.commit(). It speeds up significantly...

Thus, they theory that the in-memory index built during the transaction is a linear scan and not a log(n) structure holds more merit.

**Comment by mbroecheler** [comment] 2013-05-03 00:34
The linear scan issue has been fixed. There is no an internal "equality" index for vertex lookups maintained by the transaction. Verified the performance in test cases.

**Closed as completed by mbroecheler** 2013-05-03 00:34 UTC
Labels: bug

**Comment by hudvin** [comment] 2013-05-06 11:10
I have tested Anton's code on 0.3.1 snapshot. It's still extremely slow. I have 7000 records, and it takes about 30-60 msec to insert one relation.
Can you provide full configuration?

**Comment by hariharshankar** [comment] 2013-05-06 18:34
Titan 0.3.1-snapshot behavior confirmed. We tried loading a ~3500 vertex graph in a single transaction and the lookups and writes to the graph was very fast. Definitely not linear lookups.

**Comment by mbroecheler** [comment] 2013-05-06 18:38
@hudvin Titan 0.3.1 has extra consistency checks inside the transaction that Titan 0.2.x does not have. Also, the indexing infrastructure is slightly more involved than in the 0.2.x line due to the additional indexing support. That explains some performance difference between 0.3.x and 0.2.x but it shouldn't be much slower. What is Anton's code? Also, note that you can enable storage.batch-loading=true to get better performance when loading large amounts of data which disables consistency checks.
