### ISSUE TITLE
IllegalArgument : invalid count for upper bound

### ISSUE THREAD

**Issue by dbxfb** [thinkaurelius/titan#37] opened 2012-07-10 09:18 UTC
Hello !

While doing some hard work on my graph which loads about 1M nodes and 15M edges in memory (well, causes Titan to keep those in cache, at least),
I encountered the following exception when trying to add a few nodes and edges:

<pre>
java.lang.IllegalArgumentException: Invalid count for bound:4611686018427387903
        at com.thinkaurelius.titan.graphdb.idmanagement.IDManager.getEdgeID(IDManager.java:169)
        at com.thinkaurelius.titan.graphdb.database.idassigner.SimpleVertexIDAssigner.nextEdgeID(SimpleVertexIDAssigner.java:91)
        at com.thinkaurelius.titan.graphdb.database.idassigner.SimpleVertexIDAssigner.getNewID(SimpleVertexIDAssigner.java:52)
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.assignID(StandardTitanGraph.java:526)
        at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.registerNewEntity(AbstractTitanTx.java:111)
        at com.thinkaurelius.titan.graphdb.relations.factory.StandardPersistedRelationFactory.createNewRelationship(StandardPersistedRelationFactory.java:116)
        at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.addEdge(AbstractTitanTx.java:210)
    at (my program)
</pre>

Do you have any idea of why this may be happening?
I'm okay with fixing it by myself if need be, but I don't really understand how I ended up with such a high value in the ID counter.

Not sure if it helps, but when I manually take a look at the titan_ids CF (I'm using a Cassandra backend), I can see the latest allocated blocks:

<pre>
0 (Node) -> [2300001;2400001)
1 (Edge) -> [9900001;10000001)
2 (PropertyType) -> [1100001;1200001)
</pre>

Thanks for your time :)

**Comment by mbroecheler** [comment] 2012-07-11 07:09
Wow, that's a crazy large id. Since it's close to 2^62 I suspect its some
overflow problem, but not sure where it is coming from. Do you have a small
code snippet that reproduces this problem for me to analyze?

Thank you!

On Tue, Jul 10, 2012 at 2:18 AM, Dan Forest-Barbier <
reply@reply.github.com

> wrote:
> 
> Hello !
> 
> While doing some hard work on my graph which loads about 1M nodes and 15M
> edges in memory (well, causes Titan to keep those in cache, at least),
> I encountered the following exception when trying to add a few nodes and
> edges:
> 
> <pre>
> java.lang.IllegalArgumentException: Invalid count for
> bound:4611686018427387903
>         at
> com.thinkaurelius.titan.graphdb.idmanagement.IDManager.getEdgeID(IDManager.java:169)
>         at
> com.thinkaurelius.titan.graphdb.database.idassigner.SimpleVertexIDAssigner.nextEdgeID(SimpleVertexIDAssigner.java:91)
>         at
> com.thinkaurelius.titan.graphdb.database.idassigner.SimpleVertexIDAssigner.getNewID(SimpleVertexIDAssigner.java:52)
>         at
> com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.assignID(StandardTitanGraph.java:526)
>         at
> com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.registerNewEntity(AbstractTitanTx.java:111)
>         at
> com.thinkaurelius.titan.graphdb.relations.factory.StandardPersistedRelationFactory.createNewRelationship(StandardPersistedRelationFactory.java:116)
>         at
> com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.addEdge(AbstractTitanTx.java:210)
>         at (my program)
> </pre>
> 
> 
> Do you have any idea of why this may be happening?
> I'm okay with fixing it by myself if need be, but I don't really
> understand how I ended up with such a high value in the ID counter.
> 
> Not sure if it helps, but when I manually take a look at the titan_ids CF
> (I'm using a Cassandra backend), I can see the latest allocated blocks:
> 
> <pre>
> 0 (Node) -> [2300001;2400001)
> 1 (Edge) -> [9900001;10000001)
> 2 (PropertyType) -> [1100001;1200001)
> </pre>
> 
> 
> Thanks for your time :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thinkaurelius/titan/issues/37

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by dbxfb** [comment] 2012-07-11 15:57
I'm sorry, I did not have the time for a snippet (I'll try to write one this week).
However, I now know that I can reproduce the result each time I run this computation, and I ran it with a debugger :
- IDManager.getEdgeID(count = 9151315547450148020)
  - edgeTypeCountPartMask = 4503599627370495
  - edgeTypeIDBackLength = 11
  - groupBits = 6
  - groupIDDeltaOffset = 49
  - groupIDFrontMask = 283726776524341248
  - groupIDMask = 2269814212194729984
  - groupIDMaskTMP = 504
  - groupOffset = 55
  - inverseGroupIDMask = -2269814212194729985
  - maxEdgeID = 4611686018427387903
  - maxEdgeTypeID = 4503599627370495
  - maxGroupID = 62
  - maxNodeID = 2305843009213693951
  - maxPartitionID = 0
  - partitionBits = 0
  - partitionOffset = 63
- SimpleVertexIDAssigner.nextEdgeID()
- SimpleVertexIDAssigner.getNewID(InternalTitanVertex)
  - (maxPartitionID, offset, offsetBits) = 0
- -> this.edge (IDPool, instance of StandardIDPool)
  - bufferMaxID = -1
  - bufferNextID = -1
  - maxID = 9151315547450248020
  - nextID = (maxID + 1)
  - partitionID = 1
  - renewBufferID = (maxID)
- -> this.node // This is the internal “node”, not the vertex argument
  - bufferMaxID = 3200001
  - bufferNextID = 3100001
  - (max, next, partition, renewBuffer)ID = 0

I haven't found any cause — I thought about a possible race condition with the renewbuffer thread, but when looking at both the code and the above internal states it seems unlikely.

It might be caused by my embedded Cassandra driver, but it seems unlikely (at the moment) since everything else works fine with it, and there were no exceptions from Cassandra / StorageManager...
(I cannot do it with the regular Cassandra driver, as Thrift and its buffers add too much memory overhead -_-)

EDIT:
I have found some internal timeout from my embedded Cassandra which happened right before this exception!
However it was there only for a few executions, and most of the time there were no Cassandra-related errors/exceptions before this happened.

**Comment by dbxfb** [comment] 2012-07-12 09:01
News !
I put a really large thrift-timeout and retried my computations using the regular Cassandra driver...
And I ended up with the same exception I got in my own driver.

I think it is caused by slow garbage collecting on OldGen, which takes around 10 seconds... and causes internal Cassandra timeout whatever the driver is, since we're in the same JVM.
Well, that was an interesting waste of time :)

Leaving this here for reference:

<pre>
2012-07-11 19:07:12,429 [ScheduledTasks:1] INFO  GCInspector - GC for PS MarkSweep: 9891 ms for 1 collections, 2603204328 used; max is 4633919488
[...]

2012-07-11 19:07:12,466
com.thinkaurelius.titan.core.GraphStorageException: Exception in storage backend.
    at com.thinkaurelius.titan.diskstorage.cassandra.CassandraThriftOrderedKeyColumnValueStore.getSlice(CassandraThriftOrderedKeyColumnValueStore.java:178)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.appendResults(StandardTitanGraph.java:496)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.queryForEntries(StandardTitanGraph.java:474)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.loadRelations(StandardTitanGraph.java:217)
    at com.thinkaurelius.titan.graphdb.transaction.StandardPersistTitanTx.loadRelations(StandardPersistTitanTx.java:149)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractTitanVertex.ensureLoadedEdges(AbstractTitanVertex.java:88)
    at com.thinkaurelius.titan.graphdb.vertices.StandardTitanVertex.getRelations(StandardTitanVertex.java:61)
    at com.thinkaurelius.titan.graphdb.query.AtomicTitanQuery.properties(AtomicTitanQuery.java:416)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractTitanVertex.getProperties(AbstractTitanVertex.java:149)
    at (my program)
Caused by: TimedOutException()
    at org.apache.cassandra.thrift.Cassandra$get_slice_result.read(Cassandra.java:7296)
    at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
    at org.apache.cassandra.thrift.Cassandra$Client.recv_get_slice(Cassandra.java:552)
    at org.apache.cassandra.thrift.Cassandra$Client.get_slice(Cassandra.java:536)
    at com.thinkaurelius.titan.diskstorage.cassandra.CassandraThriftOrderedKeyColumnValueStore.getSlice(CassandraThriftOrderedKeyColumnValueStore.java:159)
    ... 46 more

2012-07-11 19:07:13,145 
java.lang.IllegalArgumentException: Invalid count for bound:4611686018427387903
    at com.thinkaurelius.titan.graphdb.idmanagement.IDManager.getEdgeID(IDManager.java:169)
    at com.thinkaurelius.titan.graphdb.database.idassigner.SimpleVertexIDAssigner.nextEdgeID(SimpleVertexIDAssigner.java:91)
    at com.thinkaurelius.titan.graphdb.database.idassigner.SimpleVertexIDAssigner.getNewID(SimpleVertexIDAssigner.java:52)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.assignID(StandardTitanGraph.java:526)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.registerNewEntity(AbstractTitanTx.java:111)
    at com.thinkaurelius.titan.graphdb.relations.factory.StandardPersistedRelationFactory.createNewProperty(StandardPersistedRelationFactory.java:66)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.addProperty(AbstractTitanTx.java:194)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractTitanVertex.addProperty(AbstractTitanVertex.java:221)
    at com.thinkaurelius.titan.graphdb.vertices.factory.StandardVertexFactories$1.createNew(StandardVertexFactories.java:22)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.addVertex(AbstractTitanTx.java:124)
    at (my program)

2012-07-11 19:07:13,146
java.lang.IllegalArgumentException: Invalid count for bound:4611686018427387903
    at com.thinkaurelius.titan.graphdb.idmanagement.IDManager.getEdgeID(IDManager.java:169)
    at com.thinkaurelius.titan.graphdb.database.idassigner.SimpleVertexIDAssigner.nextEdgeID(SimpleVertexIDAssigner.java:91)
    at com.thinkaurelius.titan.graphdb.database.idassigner.SimpleVertexIDAssigner.getNewID(SimpleVertexIDAssigner.java:52)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.assignID(StandardTitanGraph.java:526)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.registerNewEntity(AbstractTitanTx.java:111)
    at com.thinkaurelius.titan.graphdb.relations.factory.StandardPersistedRelationFactory.createNewProperty(StandardPersistedRelationFactory.java:66)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.addProperty(AbstractTitanTx.java:194)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractTitanVertex.addProperty(AbstractTitanVertex.java:221)
    at com.thinkaurelius.titan.graphdb.vertices.factory.StandardVertexFactories$1.createNew(StandardVertexFactories.java:22)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.addVertex(AbstractTitanTx.java:124)
    at (my program)
</pre>

**Comment by dbxfb** [comment] 2012-07-12 10:43
Well, fake alert. Even after changing GC settings and JVM heap size, I can reproduce the error (and it's the ONLY error happening, without Cassandra timeouts or GC longer than 200ms ...)

<pre>
     [java] java.lang.IllegalArgumentException: Invalid count for bound:4611686018427387903
     [java]     at com.thinkaurelius.titan.graphdb.idmanagement.IDManager.getEdgeID(IDManager.java:169)
</pre>


I hope you don't mind me flooding this issue :)

**Comment by mbroecheler** [comment] 2012-07-14 05:41
Absolutely not! Thanks for looking into this so carefully - this is a
really peculiar issue.

On Thu, Jul 12, 2012 at 3:43 AM, Dan Forest-Barbier <
reply@reply.github.com

> wrote:
> 
> Well, fake alert. Even after changing GC settings and JVM heap size, I can
> reproduce the error (and it's the ONLY error happening, without Cassandra
> timeouts or GC longer than 200ms ...)
> 
> <pre>
>      [java] java.lang.IllegalArgumentException: Invalid count for
> bound:4611686018427387903
>      [java]     at
> com.thinkaurelius.titan.graphdb.idmanagement.IDManager.getEdgeID(IDManager.java:169)
> </pre>
> 
> 
> I hope you don't mind me flooding this issue :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thinkaurelius/titan/issues/37#issuecomment-6932033

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by mbroecheler** [comment] 2012-08-29 22:45
Hey Dan,

do you have any news on this issue? I had hoped to be able to reproduce it once we had an embedded cassandra adapter in Titan, but no luck thus far. I did take another close look at the stack trace provided but cannot really explain where that crazy large maxID for the edge IDPool is coming from. 
Some wild thoughts:
1) Do you have multiple Titan databases running against the same cassandra backend that might experience race conditions when trying to renew the id block? Your read of the ids from the CF indicate otherwise (those look normal), but who knows...
2) the node IDPool suggests that this exception is occurring without any nodes being added, correct? So, you are adding a bunch of edges and suddenly you get this exception? What do the ids that get previously returned look like? I added some debug/trace logging to StandardIDPool. Set logging to trace and try to run your code to see when the ids start becoming crazy.

That's all I got thus far...

**Comment by mbroecheler** [comment] 2012-08-30 20:02
Another thing: In a recent commit, lazy initialization of ID pools and type specific id pool sizes where introduced. Maybe those have an impact on the behavior you are seeing, so it might be worth trying out the current head of the titan0.1 branch and see if that changes anything.
Thanks!

**Comment by mbroecheler** [comment] 2012-09-06 01:10
Closing for now...

**Closed as completed by mbroecheler** 2012-09-06 01:10 UTC
Labels: question

**Comment by dbxfb** [comment] 2012-11-06 02:55
Hi Matthias,

I am deeply sorry for not answering earlier, I started a new university semester and forgot to check github notifications...

Unfortunately I cannot look into this peculiar issue anymore, as my internship ended 2 months ago and thus I do not have either code or data available at hand :/

I can however reply to both your questions:
1) I only had 1 Titan database running on my Cassandra backend (in its own keyspace), as I was still at the r&d/prototyping stage
2) Yes, it often happened during an algorithm's massive edge creation phase !

Thanks :)
