### ISSUE TITLE
Toy example not running due to "Unknown configuration element in namespace [root.index]: local-mode" error

### ISSUE THREAD

**Issue by tomersagi** [thinkaurelius/titan#750] opened 2014-09-04 06:21 UTC
Hi,
I built from the titan05 branch and tried to run the toy example from (http://s3.thinkaurelius.com/docs/titan/0.5.0/getting-started.html)[here]. This is the result:

> $ ./gremlin.sh
> 09:00:19 WARN  org.apache.hadoop.util.NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
> gremlin> g = GraphOfTheGodsFactory.create('/tmp/titan')
> Unknown configuration element in namespace [root.index]: local-mode
> Display stack trace? [yN] y
> java.lang.IllegalArgumentException: Unknown configuration element in namespace [root.index]: local-mode
>         at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
>         at com.thinkaurelius.titan.diskstorage.configuration.ConfigElement.parse(ConfigElement.java:170)
>         at com.thinkaurelius.titan.diskstorage.configuration.UserModifiableConfiguration.set(UserModifiableConfiguration.java:81)
>         at com.thinkaurelius.titan.core.TitanFactory$Builder.set(TitanFactory.java:122)
>         at com.thinkaurelius.titan.example.GraphOfTheGodsFactory.create(GraphOfTheGodsFactory.java:33)
>         at com.thinkaurelius.titan.example.GraphOfTheGodsFactory$create.call(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
>         at groovysh_evaluate.run(groovysh_evaluate:82)
>         at groovysh_evaluate$run.call(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
>         at groovysh_evaluate$run.call(Unknown Source)
>         at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:67)
>         at org.codehaus.groovy.tools.shell.Interpreter$evaluate.call(Unknown Source)
>         at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
>         at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
>         at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
>         at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
>         at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:606)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
>         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
>         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
>         at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:606)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
>         at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
>         at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:606)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
>         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
>         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
>         at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
>         at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.Console.<init>(Console.java:61)
>         at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.Console.<init>(Console.java:68)
>         at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.Console.main(Console.java:73)

**Comment by dalaro** [comment] 2014-09-04 06:46
Hi @tomersagi, this is a duplicate of #740.  Fix has already been committed on titan05 and is forthcoming with 0.5.1.  Please see the linked issue for the workaround on 0.5.0.

**Closed as completed by dalaro** 2014-09-04 06:46 UTC
Labels: duplicate

**Comment by ariansacct** [comment] 2015-06-09 16:05
@dalaro  I'm running 0.5.4 and still get this.

`<dependency>`
`<groupId>com.thinkaurelius.titan</groupId>`
`<artifactId>titan-all</artifactId>`
`<version>0.5.4</version>`
`</dependency>`
