### ISSUE TITLE
Bug in Titan BerkeleyDB

### ISSUE THREAD

**Issue by dirkweissenborn** [thinkaurelius/titan#476] opened 2013-11-11 17:46 UTC
Graph configuration:

```
storage.backend=berkeleyje
storage.directory=$path/standard
storage.index.lucene.backend=lucene
storage.index.lucene.directory=$path/lucene
storage.buffer-size=2048
ids.block-size=500000

g.makeKey(UI).dataType(classOf[String]).indexed(classOf[Vertex]).unique(UniquenessConsistency.LOCK).make()
g.makeKey(TYPE).dataType(classOf[String]).indexed(classOf[Vertex]).indexed("lucene",classOf[Vertex]).make()
g.makeKey(TEXT).dataType(classOf[String]).indexed("lucene",classOf[Vertex]).make()
g.makeKey(SOURCE).dataType(classOf[String]).indexed(classOf[Edge]).make()
g.makeKey(WEIGHT).dataType(classOf[java.lang.Double]).indexed(classOf[Edge]).make()
g.commit()

final val UI = "ui"
final val TYPE = "type"
final val TEXT = "text"
final val SOURCE = "source"
final val WEIGHT = "weight"

//open/create graph
graph = TitanFactory.open(titanConf)
```

I filled the graph with my data and tested the following with gremlin:

```
gremlin> g.v(252).ui
==>C0033684
gremlin> g.v(724).ui
==>C0033684
gremlin> g.v(1016).ui
==>C0033684
gremlin> g.v(7644).ui
==>C0033684
```

This should not be possible after the given type declaration, that 'ui' should be unique. During indexing, I query the graph for a given vertex with the given 'ui'. If it exists, I take it and add an edge to it. If not I create it first.

This is how I query the graph for the vertex:

```
val it1 = graph.query.has('ui', Compare.EQUAL, c1.conceptId).limit(1).vertices()
```

How can it happen that there are many vertices with the same ui?

**Comment by mbroecheler** [comment] 2013-11-13 00:58
Is there something else I need to know about your setup? I am not able to reproduce this:

``` java
gremlin> g.makeKey("ui").dataType(String.class).indexed(Vertex.class).unique(TypeMaker.UniquenessConsistency.LOCK).make()
==>v[74]
gremlin> g.commit()
==>null
gremlin> g.addVertex(['ui':'C0033684'])
==>v[4]
gremlin> g.addVertex(['ui':'C0033684'])
The given value [C0033684] is already used as a property and the property key [ui] is defined as graph-unique
Display stack trace? [yN] n
gremlin> g.commit()
==>null
gremlin> g.v(4).map
==>{ui=C0033684}
gremlin> g.addVertex(['ui':'C0033684'])
The given value [C0033684] is already used as a property and the property key [ui] is defined as graph-unique
Display stack trace? [yN] n
```

where my config file is a copy of yours with a specific path:

``` text
storage.backend=berkeleyje
storage.directory=db
storage.index.lucene.backend=lucene
storage.index.lucene.directory=$path/lucene
storage.buffer-size=2048
ids.block-size=500000
```

**Comment by dirkweissenborn** [comment] 2013-11-13 10:37
Well, there is nothing else to add from my side. Just wanted to share that I found this problem even though it should not be possible. I solved this by keeping a 'ui' to 'id' map on my side in memory and just lookup ids, whenever I want to add a vertex. I was not running any concurrent writing operations and transactions was not set to false.

**Comment by mbroecheler** [comment] 2013-11-13 18:42
Mmmh, strange. I assume storage.batch-graph wasn't enabled either? Can you share the script and a fragment of the data that reproduces the problem for us to look at? I wasn't able to reproduce it with a pseudo replication of what you did.

**Comment by dirkweissenborn** [comment] 2013-11-13 19:02
I already changed the code to fix that problem. But I will try to get it back for you.

**Comment by dirkweissenborn** [comment] 2013-11-13 19:03
I already changed the code to fix that problem. But I will try to get it
back for you.

2013/11/13 Matthias Broecheler notifications@github.com

**Comment by mbroecheler** [comment] 2014-01-15 22:55
Any news on this issue @dirkweissenborn ? Could it be the same as: #501

**Comment by dirkweissenborn** [comment] 2014-01-15 23:00
No. Did not encounter it again. But I am still using my workaround, which
prevents that from happening.

**Comment by mbroecheler** [comment] 2015-06-24 18:59
It seems that the last incarnations of this are a duplicate of #501 which has a dependency on BDB.

**Closed as completed by mbroecheler** 2015-06-24 18:59 UTC
Labels: bug, duplicate, dependency
