### ISSUE TITLE
a problem of cassandra consistency

### ISSUE THREAD

**Issue by boliza** [thinkaurelius/titan#811] opened 2014-11-09 11:51 UTC
Under certain scenarios,that's cassandra consistency is incorrect,we can't open the graph instance,by consistency quorum(r = 3).

**Comment by mbroecheler** [comment] 2014-11-13 00:45
Can you elaborate on the problem that you are seeing? If the Cassandra cluster drops below quorum, that would be expected behavior.

**Comment by boliza** [comment] 2014-11-13 13:13
Today I watch the log of cassandra then I find there many ERROR about tombstone time out。

```
ERROR [ReadStage:35020] 2014-11-13 21:07:43,677 CassandraDaemon.java (line 199) Exception in thread Thread[ReadStage:35020,5,main]
java.lang.RuntimeException: org.apache.cassandra.db.filter.TombstoneOverwhelmingException
    at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:1931)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: org.apache.cassandra.db.filter.TombstoneOverwhelmingException
    at org.apache.cassandra.db.filter.SliceQueryFilter.collectReducedColumns(SliceQueryFilter.java:202)
    at org.apache.cassandra.db.filter.QueryFilter.collateColumns(QueryFilter.java:122)
    at org.apache.cassandra.db.filter.QueryFilter.collateOnDiskAtom(QueryFilter.java:80)
    at org.apache.cassandra.db.filter.QueryFilter.collateOnDiskAtom(QueryFilter.java:72)
    at org.apache.cassandra.db.CollationController.collectAllData(CollationController.java:297)
    at org.apache.cassandra.db.CollationController.getTopLevelColumns(CollationController.java:53)
    at org.apache.cassandra.db.ColumnFamilyStore.getTopLevelColumns(ColumnFamilyStore.java:1547)
    at org.apache.cassandra.db.ColumnFamilyStore.getColumnFamily(ColumnFamilyStore.java:1376)
    at org.apache.cassandra.db.Keyspace.getRow(Keyspace.java:333)
    at org.apache.cassandra.db.SliceFromReadCommand.getRow(SliceFromReadCommand.java:65)
    at org.apache.cassandra.service.StorageProxy$LocalReadRunnable.runMayThrow(StorageProxy.java:1363)
    at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:1927)
    ... 3 more

```

I debug my program,found that titan can't read the CF system_properties.The logger is

```
at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:308)[11:org.apache.felix.fileinstall:3.2.8]
Caused by: com.thinkaurelius.titan.core.TitanException: Could not execute operation due to backend exception
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:44)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:144)
    at com.thinkaurelius.titan.diskstorage.configuration.backend.KCVSConfiguration.toMap(KCVSConfiguration.java:166)
    at com.thinkaurelius.titan.diskstorage.configuration.backend.KCVSConfiguration.asReadConfiguration(KCVSConfiguration.java:187)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1272)
```

I use to truncate the CF system_properties to slove this problem,that's works.

**Comment by dalaro** [comment] 2014-12-19 11:26
@boliza Is this reproducible?

Cassandra's `tombstone_failure_threshold` is configurable, but I'm assuming it's at the default value of 100k.  Accumulating 100k tombstones on `system_properties` seems highly unusual.  I can't think of a natural use case that should do that specifically to `system_properties`.  TombstoneOverwhelmingException on `edgestore` does occasionally come up in busy ingest/modify use cases, and that often has a reasonable explanation, but to have it on `system_properties` seems pretty odd.  I think this is the first time I've seen TOE on `system_properties`.  I was unable to find something similar in a brief search of past issues and threads.  If there's an underlying issue in Titan here, then I want to troubleshoot it, but right now I don't see one.

For those who find this issue through Google: you don't necessarily have to truncate `system_properties` to fix this.  Do not truncate it unless you're also deleting the entire Titan DB and starting from scratch.  One alternative to truncation is to decrease `gc_grace_seconds` and then run a compaction.  The Cassandra docs have more info on that.

**Comment by boliza** [comment] 2014-12-19 15:31
@dalaro I have many instance of my titan application.REST API,Vertex Persitence,Graph analysis.maybe Some of this instance config is not the same.When I upgrade to tian0.52,I have't see the exception anymore(I have not run the gemlin command again)

**Comment by boliza** [comment] 2014-12-22 11:22
@dalaro I use cassandra2.0.9,tombstone_failure_threshold is 100k.

**Comment by dalaro** [comment] 2014-12-23 14:05
Since I'm unsure how to reproduce this one, and since I don't currently see how it would happen on `system_properties` in typical use patterns, I'm going to close this.  But please reopen if it recurs or if you have more info about the last occurrence that could help us troubleshoot.

**Closed as completed by dalaro** 2014-12-23 14:05 UTC

**Comment by boliza** [comment] 2014-12-23 17:26
Thank for your work.
