### ISSUE TITLE
Inconsistent Transactional Scopes for Traversal

### ISSUE THREAD

**Issue by spmallette** [thinkaurelius/titan#871] opened 2014-12-04 13:32 UTC
Certain traversals seem to execute within different scopes.  This causes problems for Gremlin Server, but also might yield some weirdness for folks in other contexts.  You can recreate the issue from the console pretty easily.  The following sets up the graph:

``` text
gremlin> g = TitanFactory.open("conf/titan-berkeleydb.properties")
==>standardtitangraph[berkeleyje:/home/smallette/jvm/titan-console-0.9.0-M0/conf/db/berkeley]
gremlin> g.addVertex("name","stephen")
==>v[256]
gremlin> g.tx().commit()
==>null
gremlin> g.V()
==>v[256]
gremlin> g.V().filter{it.get().value('name')=='stephen'}
==>v[256]
gremlin> g.V().has('name','stephen')
==>v[256]
```

That all works nicely, but if i do a `g.tx().rollback()` my `Traversal` is invalidated:

``` text
gremlin> t=g.V().filter{it.get().value('name')=='stephen'};null
==>null
gremlin> g.tx().rollback()
==>null
gremlin> t
==>v[256]
gremlin> t = g.V().has('name','stephen');null
==>null
gremlin> g.tx().rollback()
==>null
gremlin> t
Operation cannot be executed because the enclosing transaction is closed
Display stack trace? [yN] y
java.lang.IllegalStateException: Operation cannot be executed because the enclosing transaction is closed
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.verifyOpen(StandardTitanTx.java:270)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.getRelationType(StandardTitanTx.java:845)
    at com.thinkaurelius.titan.graphdb.query.QueryUtil.getType(QueryUtil.java:64)
    at com.thinkaurelius.titan.graphdb.query.QueryUtil.constraints2QNF(QueryUtil.java:177)
    at com.thinkaurelius.titan.graphdb.query.graph.GraphCentricQueryBuilder.constructQuery(GraphCentricQueryBuilder.java:193)
    at com.thinkaurelius.titan.graphdb.query.graph.GraphCentricQueryBuilder.vertices(GraphCentricQueryBuilder.java:140)
    at com.thinkaurelius.titan.graphdb.tinkerpop.optimize.TitanGraphStep.generateTraversers(TitanGraphStep.java:45)
    at com.tinkerpop.gremlin.process.graph.strategy.TraverserSourceStrategy.lambda$apply$355(TraverserSourceStrategy.java:50)
    at com.tinkerpop.gremlin.process.graph.strategy.TraverserSourceStrategy$$Lambda$25/1286437308.accept(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at com.tinkerpop.gremlin.process.graph.strategy.TraverserSourceStrategy.apply(TraverserSourceStrategy.java:50)
    at com.tinkerpop.gremlin.process.util.DefaultTraversalStrategies.lambda$apply$451(DefaultTraversalStrategies.java:41)
    at com.tinkerpop.gremlin.process.util.DefaultTraversalStrategies$$Lambda$10/700546109.accept(Unknown Source)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at com.tinkerpop.gremlin.process.util.DefaultTraversalStrategies.apply(DefaultTraversalStrategies.java:41)
    at com.tinkerpop.gremlin.process.util.DefaultTraversal.applyStrategies(DefaultTraversal.java:44)
    at com.tinkerpop.gremlin.process.util.DefaultTraversal.hasNext(DefaultTraversal.java:76)
    at com.tinkerpop.gremlin.console.Console$_closure3.doCall(Console.groovy:155)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at org.codehaus.groovy.tools.shell.Groovysh.setLastResult(Groovysh.groovy:370)
    at org.codehaus.groovy.tools.shell.Groovysh.this$3$setLastResult(Groovysh.groovy)
    at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:215)
    at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:159)
    at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:121)
    at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:93)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:130)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:150)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:123)
    at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:130)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:150)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:83)
    at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:215)
    at com.tinkerpop.gremlin.console.Console.<init>(Console.groovy:99)
    at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:636)
    at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:215)
    at com.tinkerpop.gremlin.console.Console.main(Console.groovy:252)
```

Seems strange that one `Traversal` works but the other does not.  I'm not sure if other steps trigger this issue.  Gremlin Server would be happy if `t` could be iterated outside of the transaction it was initialized in (e.g. `has` should behave like `filter` in the example above).

**Comment by mbroecheler** [comment] 2015-01-21 19:11
Duplicate of #921

**Closed as completed by mbroecheler** 2015-01-21 19:11 UTC
