### ISSUE TITLE
Error executing example queries.

### ISSUE THREAD

**Issue by angelcervera** [thinkaurelius/titan#866] opened 2014-12-03 11:17 UTC
When I try to execute the example about indexes: https://github.com/thinkaurelius/titan/wiki/Indexing-Backend-Overview throws an exception:
g.query().has("age",GREATER_THAN_EQUAL,1000).has("age",LESS_THAN,5000).orderBy("age",Order.ASC).vertices()

==>javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: GREATER_THAN_EQUAL for class: Script10

The same for Order and LESS_THAN
==>javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: Order for class: Script9

**Comment by mbroecheler** [comment] 2014-12-03 23:36
If you are running this through the gremlin-groovy adapter, try T.gte and
T.lt instead.

On Wed, Dec 3, 2014 at 3:17 AM, Ángel Cervera Claudio <
notifications@github.com> wrote:

> When I try to execute the example about indexes:
> https://github.com/thinkaurelius/titan/wiki/Indexing-Backend-Overview
> throws an exception:
> 
> g.query().has("age",GREATER_THAN_EQUAL,1000).has("age",LESS_THAN,5000).orderBy("age",Order.ASC).vertices()
> 
> ==>javax.script.ScriptException: groovy.lang.MissingPropertyException: No
> such property: GREATER_THAN_EQUAL for class: Script10
> 
> The same for Order and LESS_THAN
> ==>javax.script.ScriptException: groovy.lang.MissingPropertyException: No
> such property: Order for class: Script9
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/866.

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by angelcervera** [comment] 2014-12-04 06:51
Where I can found documentation about this?

**Comment by dalaro** [comment] 2014-12-15 17:41
@angelcervera Here's the javadoc for `T` as of Gremlin 2.5.0: http://www.tinkerpop.com/docs/javadocs/gremlin/2.5.0/com/tinkerpop/gremlin/Tokens.T.html

**Comment by dalaro** [comment] 2014-12-15 17:43
@angelcervera What version are you using?  The documentation on the Github wiki is for 0.4.x (master branch).  You recently commented in #869 that you were using "5.0.2" which I assume meant 0.5.2.  The manual for 0.5.2 is here: http://s3.thinkaurelius.com/docs/titan/0.5.2/

**Comment by dalaro** [comment] 2014-12-17 07:52
I can't reproduce this problem in gremlin.sh or rexster-console.sh 0.5.2.

The 0.5.2 manual still contains the queries you found on the github wiki here:

http://s3.thinkaurelius.com/docs/titan/0.5.2/search-predicates.html

But all of the queries on that page evaluate in gremlin.sh and rexster-console.sh on 0.5.2, including the GREATER_THAN_EQUAL ones.

Did you download the rexster zipfile separately, then install Titan as an extension, and then run rexster-console.sh to try these queries?  That might explain what's going on.  Just a guess.  Closing this since I can't reproduce it, but please reopen if you have details to share.

**Closed as completed by dalaro** 2014-12-17 07:52 UTC
