### ISSUE TITLE
Multi-threaded reads do not see changes in titan-core 0.3.2

### ISSUE THREAD

**Issue by mpouttuclarke** [thinkaurelius/titan#404] opened 2013-09-30 19:07 UTC
If I write changes in a new thread and read the changes in a separate thread (other than main thread) the changes cannot be seen.  See attached code example:

**Comment by mpouttuclarke** [comment] 2013-09-30 19:08
import java.io.File;
import java.util.Iterator;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.BlockingQueue;

import org.apache.commons.configuration.BaseConfiguration;
import org.apache.commons.configuration.Configuration;
import org.apache.commons.io.FileUtils;

import com.thinkaurelius.titan.core.TitanFactory;
import com.thinkaurelius.titan.core.TitanGraph;
import com.thinkaurelius.titan.core.TitanTransaction;
import com.thinkaurelius.titan.core.TitanVertex;
import com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration;
import com.tinkerpop.blueprints.Direction;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.util.ElementHelper;

public class SimpleLoad {

```
/**
 * @param args
 */
public static void main(String[] args) throws Exception {
    BaseConfiguration config = new BaseConfiguration();
    Configuration storage = config
            .subset(GraphDatabaseConfiguration.STORAGE_NAMESPACE);
    File file = new File(args[0]);
    FileUtils.deleteDirectory(new File("target/test"));
    storage.setProperty("cassandra-config-dir", file.toURI()
            .toURL().toString());
    storage.setProperty(GraphDatabaseConfiguration.STORAGE_BACKEND_KEY,
            "embeddedcassandra");

    final TitanGraph graph = TitanFactory.open(config);
    graph.makeType().name("cid").dataType(Long.class)
            .indexed(Vertex.class).unique(Direction.BOTH)
            .makePropertyKey();
    graph.makeType().name("fullName").dataType(String.class)
            .unique(Direction.OUT).makePropertyKey();

    graph.commit();

    final BlockingQueue<Long> ids = new ArrayBlockingQueue<Long>(1);
    Thread writer = new Thread(new Runnable() {
        @Override
        public void run() {
            TitanTransaction tx = graph.newTransaction();
            TitanVertex v = (TitanVertex) tx.addVertex(null);
            ElementHelper.setProperties(v, "cid", 1L, "fullName",
                    "jimbo");
            ids.add((Long)v.getProperty("cid"));
            tx.commit();
        }
    });
    writer.start();

    Thread reader = new Thread(new Runnable() {
        @Override
        public void run() {
            Long id;
            try {
                id = ids.take();
            } catch (InterruptedException e) {
                throw new IllegalStateException(e);
            }
            System.out.println("Got cid: " + id);
            Iterator<Vertex> i = graph.newTransaction().query()
                    .has("cid", id).vertices()
                    .iterator();
            if (i.hasNext()) {
                Vertex v2 = i.next();
                System.out.println("Inside of thread: " + v2.getProperty("fullName"));
            } else {
                System.out.println("Inside of thread: nothing");
            }
        }
    });

    reader.start();

    reader.join();
    writer.join();

    Iterator<Vertex> i = graph.newTransaction().query()
            .has("cid", 1L).vertices()
            .iterator();
    if (i.hasNext()) {
        Vertex v2 = i.next();
        System.out.println("Outside of thread: " + v2.getProperty("fullName"));
    } else {
        System.out.println("Outside of thread: nothing");
    }
}
```

}

**Comment by mpouttuclarke** [comment] 2013-09-30 19:10
Currently, running the command line results in:
java -javaagent:C:\Development\Dependencies.m2\repository\com\github\stephenc\jamm\0.2.5\jamm-0.2.5.jar -Xmx4g SimpleLoad src/test/resources/disk-cassandra.yaml
Got cid: 1
Inside of thread: nothing
Outside of thread: jimbo

The second to last line should read:
Inside of thread: jimbo

**Comment by mbroecheler** [comment] 2013-10-01 03:43
Yes, that's the whole point of transactions. The changes in a transaction only become visible when the transaction commits. Before then, those changes are tentative and can always be discarded with rollback().
Since your reader starts right after you writer, the writer might not have committed yet. If you introduce a Thread.sleep(x) after writer.start() and slowly increase x from 0, the reader should start seeing the data.

**Comment by dalaro** [comment] 2013-10-01 17:05
Transactions are safe for [concurrent use by multiple threads](https://github.com/thinkaurelius/titan/wiki/Multi-Threaded-Transactions), just in case somebody stumbles on this issue and wonders.

I think you could get your program's intended behavior by either:
- making the reader and writer threads share a single transaction instead of calling `newTransaction()` separately in each of them; you would probably commit this shared tx after joining both threads from main
- moving `ids.add(...)` after `tx.commit()` in the writer; the vertex object stales on commit, so you either have to keep the new `cid` value in memory or read it back from the database in second transaction after committing the first one

**Comment by mpouttuclarke** [comment] 2013-10-01 17:32
Thanks!  From your description I found the error in my code and fixed it.  I now have the benchmark running against embedded Cassandra with Fusion-io storage.  I’ll publish the results within the next couple of days.

**Closed as completed** 2013-10-15 16:41 UTC
