### ISSUE TITLE
Is it possible to run Titan on BigTable?

### ISSUE THREAD

**Issue by jturmel** [thinkaurelius/titan#1117] opened 2015-07-04 18:53 UTC
They use the HBase API, but have some slight differences.

HBase differences: https://cloud.google.com/bigtable/docs/hbase-differences

**Comment by mbroecheler** [comment] 2015-07-10 18:21
I think it should technically be possible to implement KeyValueStore against BigTable.

**Comment by ghost** [comment] 2015-12-16 18:49
This is now a duplicate of 1203.  Recommend we close either this one or 1203, and not sure this needs an issue open against Titan, unless the idea is Titan include a titan-bigtable module, which doesn't seem like a good idea.

**Comment by spmallette** [comment] 2015-12-16 19:04
Closing in favor #1203 as @graben1437 suggested.

**Closed as completed by spmallette** 2015-12-16 19:04 UTC

**Comment by jturmel** [comment] 2015-12-17 15:49
Seems weird since this one was opened/existed first... but anyhow. :smile:

**Comment by spmallette** [comment] 2015-12-17 15:59
If it makes you feel any better, I suspect the other will be closed as well before we're all done going through issues. :)  

When it comes to new backends for Titan, we generally like to see folks develop those externally in their own repositories, get community feedback and then watch how it evolves.  Amazon did this nicely.  I think MapDB has an implementation in the works like that.

**Comment by jturmel** [comment] 2015-12-18 13:16
I know, mostly kidding.

**Comment by mbrukman** [comment] 2017-05-20 19:06
@jturmel, @graben1437 — you can use [JanusGraph](https://github.com/JanusGraph/janusgraph) (fork of Titan) together with [Bigtable](https://cloud.google.com/bigtable/); see [JanusGraph + Bigtable docs](http://docs.janusgraph.org/latest/bigtable.html) for configuration details.
