### ISSUE TITLE
Titan 0.5.4 backend index configuration issue

### ISSUE THREAD

**Issue by MFrancesco** [thinkaurelius/titan#997] opened 2015-04-08 08:57 UTC
Hi all, using titan 0.5.4 on hbase with solr secondary index here.

Currently i'm struggling finding the right configuration in order to make some unit test for my application.
I have 2 identical collection in my solr installation:
search and searchtest and i would like to use the second one for some unit testing.

To use solr as secondary index config i need to configure properly my titan graph, 
and everythink works correctly when using and configuring my graph with the following options:

storage.backend=hbase
storage.hbase.table=titanTest
storage.hostname=localhost
index.search.backend=solr
index.search.solr.mode=http
index.search.solr.http-urls=http://localhost:8983/solr/search
index.search.solr.key-field-names=search=id

telling that my secondary index (and solr collection) will be named search.

Now i would like to use another solr collection form my unit test, named searchtest and i'm building the titangraph opening it with following configurations:

storage.backend=hbase
storage.hbase.table=titanTest
storage.hostname=localhost
index.searchtest.backend=solr
index.searchtest.solr.mode=http
index.searchtest.solr.http-urls=http://localhost:8983/solr/searchtest
index.searchtest.solr.key-field-names=searchtest=id

This configuration BTW leads to an  java.lang.IllegalStateException with the following stacktrace:

```
java.lang.IllegalStateException: Need to set configuration value: root.index.solr.key-field-names
    at com.google.common.base.Preconditions.checkState(Preconditions.java:177)
    at com.thinkaurelius.titan.diskstorage.configuration.ConfigOption.get(ConfigOption.java:158)
    at com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration.get(BasicConfiguration.java:56)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1351)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:93)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:61)
```

I have debugged it and it crash when trying to fetch the property solr.key-field-names
In GraphDatabaseConfiguration.java:1351 when it makes

```
Object storeValue = globalWrite.get(opt, pid.umbrellaElements);
```

where pid.umbrellaElements is correctly setted as searchtest, our backend index name.

I even tried to remove from the configuration this entry 
index.searchtest.solr.key-field-names=searchtest=id

but if i do this titan is going to use elasticSearch as secondary index backend ignoring all other configuration options, particularly the index.searchtest.backend=solr one's that is telling to use solr as secondary index for the index searchtest.

Any of you has suggestion on how to solve this?
How to use another secondary index in solr not named search?

**Another import thing is that these problems are not encountered when using as storage backend , inmemory.**

Infact creating a graph with code like this is ok.

```
        String solarCollectionName = "searchtest";
        TitanFactory.Builder config = TitanFactory.build();
        config.set("storage.backend", "inmemory");
        config.set("storage.directory", DEFAULT_SEARCH_INDEX_DIR);
        config.set("index."+solarCollectionName+".backend", "solr");
        config.set("index."+solarCollectionName+".solr.mode", "http");
        config.set("index."+solarCollectionName+".solr.http-urls",SOLR_DEFAULT_ADDRESS+"/"+solarCollectionName);
        config.set("index."+solarCollectionName+".solr.key-field-names",solarCollectionName+"=id");
        return config.open();
```

**Comment by dalaro** [comment] 2015-04-11 04:59
Note that switching between two different Solr indexes covering a single HBase table ("titanTest") can be problematic.  If you write data on one index then switch to the other index, subsequent queries may generate spurious index misses until repaired.

Moving on: I'm unable to reproduce an IllegalStateException here using your two configs in order.  Can you provide more detailed steps about what you're doing?  Please also note which versions of Solr and HBase you're using.

**Comment by MFrancesco** [comment] 2015-04-15 09:23
Hi, i created a [github project](https://github.com/MFrancesco/titanSolrIssue) in order to describe and reproduce the problem as better as possible. 
Just take a look at unit test, the ones with the index named searchtest fails.

About using same hbase table with different indexes i'm aware of that and i'm not going to do that, thanks.

**Comment by dalaro** [comment] 2015-04-16 04:51
Thank you, I'll take a look.

**Comment by dalaro** [comment] 2015-04-21 00:18
I looked at the GraphTest.testSearch(test)Index methods.  I tweaked the scripts a bit and got it running, although I'm having trouble getting repeatable results across multiple `mvn clean test` invocations without deleting the solr and hbase directories.

There's something wrong with the test configuration.  `src/test/resources/titan-hbase-searchtest.properties` looks like this:

``````
```
storage.backend=hbase
storage.hostname=localhost

#Table in which the graph is going to be saved
storage.hbase.table=titanTest

#Cache stuff
cache.db-cache = true
cache.db-cache-clean-wait = 20
cache.db-cache-time = 180000
cache.db-cache-size = 0.5

#Secondary index stuff
index.searchtest.backend=solr
index.searchtest.solr.mode=http
index.searchtest.solr.http-urls=http://localhost:8983/solr/searchtest
index.search.solr.key-field-names=searchtest=id
```
``````

The very last line should read `index.searchtest.solr....` not `index.search.solr...`.  When I change that, the tests pass.  There does seem to be a lot of test state outside target, by the way -- I have to manually delete /tmp/hbase-$USER and the solr and hbase install directories used by the test scripts (I moved them out of opt, but the ones in the scripts would be under /opt/apache/hbase and /opt/solr).

I don't see a Titan issue in here yet.

**Comment by mbroecheler** [comment] 2015-06-24 19:07
@MFrancesco Any other issues here or can we close this?

**Comment by MFrancesco** [comment] 2015-06-25 19:16
Let's close it, thanks

2015-06-24 21:07 GMT+02:00 Matthias Broecheler notifications@github.com:

**Closed as completed** 2015-06-25 22:34 UTC
