### ISSUE TITLE
NullPointerException  in TitanHadoop 0.5.1

### ISSUE THREAD

**Issue by skiefer** [thinkaurelius/titan#786] opened 2014-10-16 13:00 UTC
While executing a simple TitanHadoop query (g.V.has("propertyName")) the following NullPointerException occurs in TitanHadoopGraph:

``` text
2014-10-16 13:32:58.677  WARN 25498 [Thread-884] --- org.apache.hadoop.mapred.LocalJobRunner : job_local1082010068_0001

java.lang.Exception: java.lang.RuntimeException: java.lang.NullPointerException
    at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:354)
java.lang.RuntimeException: java.lang.NullPointerException
    at com.thinkaurelius.titan.hadoop.formats.util.TitanHadoopGraph.readHadoopVertex(TitanHadoopGraph.java:110)
    at com.thinkaurelius.titan.hadoop.formats.cassandra.TitanCassandraHadoopGraph.readHadoopVertex(TitanCassandraHadoopGraph.java:30)
    at com.thinkaurelius.titan.hadoop.formats.cassandra.TitanCassandraRecordReader.nextKeyValue(TitanCassandraRecordReader.java:50)
    at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:531)
    at org.apache.hadoop.mapreduce.MapContext.nextKeyValue(MapContext.java:67)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:144)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:364)
    at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:223)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
    at com.thinkaurelius.titan.hadoop.StandardFaunusRelation.setProperty(StandardFaunusRelation.java:37)
    at com.thinkaurelius.titan.hadoop.FaunusElement.setProperty(FaunusElement.java:266)
    at com.thinkaurelius.titan.hadoop.formats.util.TitanHadoopGraph.readHadoopVertex(TitanHadoopGraph.java:97)
    ... 13 common frames omitted
```

The NullPointerException is thrown because the FaunusSchemaManager is not able to resolve properties we created via the TitanManagementSystem before the job runs.

``` java
...
TitanManagement titanManagement = graph.getManagementSystem();
titanManagement.makePropertyKey(META_ATTRIBUTE_TYPE).dataType(String.class).make();
titanManagement.commit();
...
```

When using Titan 0.5.0 the job runs without any problems.

**Comment by dalaro** [comment] 2014-10-17 00:06
I reproduced this as described using GotG and the `name` property:
1. Start gremlin.sh
2. g = HadoopFactory.open('conf/hadoop/titan-cassandra-output.properties') ; g._ ; g.shutdown
3. g = HadoopFactory.open('conf/hadoop/titan-cassandra-input.properties') ; g.V.has('name').map 
4. Restart gremlin.sh
5. g = HadoopFactory.open('conf/hadoop/titan-cassandra-input.properties') ; g.V.has('name').map

The first g.V.has('name').map returns as expected, but the second (after restarting gremlin.sh) throws the NPE pasted in the report.  This only happens under 0.5.1.  The same steps under 0.5.0 do not cause this behavior.  I only tested the -hadoop2 distro for each version, but I doubt this is Hadoop-version-sensitive.  I'll investigate further.

**Comment by dalaro** [comment] 2014-11-12 23:02
This specific bug is fixed by 7243d05e0c7a4162d5750374fe02aa94b17a8850.  The bug was an unintended side-effect of 3257577f892d3479955597ba4c835f860c34f3bc, which itself fixed a different NPE while introducing this one.

This bug is somewhat unusual in that it was triggered by a VM restart.  There's no test that would catch a regression of this bug right now.

**Comment by dalaro** [comment] 2014-11-15 00:22
Since the Faunus type code is somewhat fragile, and since this bug was hidden in the absence of a VM restart between type definition and the Faunus job that used the schema, I'm keeping this open until we have a test that exercises this scenario.  A VM restart is the common case, and this bug shows that it can be affected by bugs hidden in a simple single-VM JUnit/MRUnit test.

**Comment by dalaro** [comment] 2014-11-18 06:45
I added a test for this in the titan-dist module.  This module has some Expect-based integration tests that simulate user interaction with `titan.sh` and `gremlin.sh`.  Catching a regression on this bug requires a JVM restart in the middle of the test logic, so the Expect-based integration tests seemed a more natural place to implement it than JUnit tests (even with Failsafe).  The test runs in the aurelius-release profile.  

To check this, I temporarily reversed the effects of 7243d05e0c7a4162d5750374fe02aa94b17a8850 with `git show -p 7243d05e0c7a4162d5750374fe02aa94b17a8850 | patch -p1 -R` and then recompiled the project and ran the test with `mvn clean install -DskipTests=true && cd titan-dist && mvn clean install -Dit.test='#testGraphOfTheGodsWithVMRestart' -Paurelius-release -Dgpg.skip=true`.

**Closed as completed by dalaro** 2014-11-18 06:45 UTC
Labels: bug
