### ISSUE TITLE
Titan 0.4.2 cannot getting in-edges using explicit label

### ISSUE THREAD

**Issue by anvie** [thinkaurelius/titan#616] opened 2014-03-23 00:54 UTC
I have strange experience when using Titan 0.4.2 + Cassandra  1.2.9. Cannot getting in-edges using explicit label but after querying without any label (query all in-edges) the next query using explicit label is fine.

Here is my gremlin code that demonstrating the problem:

``` groovy
gremlin> v = db.V("__id",210012111).next()
==>v[21165864]
gremlin> v.in("response_of").count()
==>0
gremlin> v.in("response_of")
gremlin> v.inE("response_of").count()
==>0
gremlin> v.inE // <-- after this all goes fine as expected
....
==>e[q7oIT-btC-98][44120-likes->21165864]
==>e[q7oIX-1yMI-98][372044-likes->21165864]
==>e[q7oJP-1qOcY-2fs][21165868-response_of->21165864] // <-- exists!
==>e[q7oKF-1qOd2-2fs][21165872-response_of->21165864] // <-- exists!
gremlin> v.inE("response_of").count()
==>2
gremlin> v.inE("response_of")
==>e[q7oJP-1qOcY-2fs][21165868-response_of->21165864]
==>e[q7oKF-1qOd2-2fs][21165872-response_of->21165864]
gremlin> v.in("response_of").count()
==>2
```

Is this bug? Or I doing some missconfiguration in Backend?
Thx for advance.

**Comment by mbroecheler** [comment] 2014-04-02 18:26
Yes, that looks very strange. Do you have a small dataset to reproduce this on?
Thanks

**Comment by mbroecheler** [comment] 2014-04-30 08:42
works for me. Closing unless there is some data to reproduce this.

``` groovy
g = gremlin> g = TitaFactory.open('/tmp/titan')
No such property: TitanFAcFactory for class: groovysh_evaluate
Display stack trace? [yN] n
gremlin> g = TitanFactory.open('/tmp/titan')
==>titangraph[local:/tmp/titan]
gremlin> v1 = g.addVertex(['__id',234234234])
==>v[4]
gremlin> v2 = g.addVertex(['__id',234224234])
==>v[8]
gremlin> v3 = g.addVertex(['__id',234224534])
==>v[12]
gremlin> v4 = g.addVertex(['__id',234224774])
==>v[16]
gremlin> v5 = g.addVertex(['__id',234224784])
==>v[20]
gremlin> v2.addEdge('response_of',v1)
==>e[B-8-1g][8-response_of->4]
gremlin> v3.addEdge('response_of',v1)
==>e[D-c-1g][12-response_of->4]
gremlin> v4.addEdge('likes',v1)
==>e[13-g-1o][16-likes->4]
gremlin> v5.addEdge('likes',v1)
==>e[15-k-1o][20-likes->4]
gremlin> g.commit()
==>null
gremlin> exit
matthiass-mbp:titan-all-0.4.2 matthias$ ./bin/gremlin.sh

         \,,,/
         (o o)
-----oOOo-(_)-oOOo-----
gremlin> g = TitanFactory.open('/tmp/titan')
==>titangraph[local:/tmp/titan]
gremlin> g.V.count()
WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
==>5
gremlin> g.commit()
==>null
gremlin> v1 = g.v(4)
==>v[4]
gremlin> v1.in('response_of').count()
==>2

```

**Closed as completed by mbroecheler** 2014-04-30 08:42 UTC
