### ISSUE TITLE
Issue generating unique instance id during Hadoop job run (0.5.x)

### ISSUE THREAD

**Issue by philmes** [thinkaurelius/titan#846] opened 2014-11-24 14:21 UTC
When running a Hadoop job against a Cassandra backed Titan graph, I occasionally get this exception: 

```
Error: java.lang.IllegalArgumentException: Could not instantiate implementation: com.thinkaurelius.titan.hadoop.formats.util.input.current.TitanHadoopSetupImpl
    at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:55)
    at com.thinkaurelius.titan.hadoop.formats.util.TitanInputFormat.getGraphSetup(TitanInputFormat.java:49)
    at com.thinkaurelius.titan.hadoop.formats.cassandra.TitanCassandraRecordReader.initialize(TitanCassandraRecordReader.java:44)
    at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.initialize(MapTask.java:525)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:763)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:340)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:167)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1554)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:44)
    ... 10 more
Caused by: com.thinkaurelius.titan.core.TitanException: A Titan graph with the same instance id [0a64088615932-preference-graph-21] is already open. Might required forced shutdown.
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:128)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:91)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:81)
    at com.thinkaurelius.titan.hadoop.formats.util.input.current.TitanHadoopSetupImpl.<init>(TitanHadoopSetupImpl.java:39)
    ... 15 more
```

My cluster has 5 workers, with each capable of running 10 simultaneous Yarn processes. These exception only happen a few times during a run, and the job does actually complete due to Hadoops retry mechanism.

**Comment by philmes** [comment] 2014-11-24 14:23
My job configuration looks like this:

```
# input graph parameters
titan.hadoop.input.format=com.thinkaurelius.titan.hadoop.formats.cassandra.TitanCassandraInputFormat
titan.hadoop.input.conf.storage.backend=cassandrathrift
titan.hadoop.input.conf.storage.hostname=preference-graph-1
titan.hadoop.input.conf.storage.port=9160
titan.hadoop.input.conf.storage.cassandra.keyspace=preference_graph
cassandra.input.partitioner.class=org.apache.cassandra.dht.Murmur3Partitioner
cassandra.input.split.size=20000
cassandra.thrift.framed.size_mb=49
cassandra.thrift.message.max_size_mb=50

titan.hadoop.sideeffect.format=org.apache.hadoop.mapreduce.lib.output.TextOutputFormat
titan.hadoop.output.format=com.thinkaurelius.titan.hadoop.formats.graphson.GraphSONOutputFormat

mapreduce.output.fileoutputformat.compress=true
```

**Comment by mbroecheler** [comment] 2014-11-24 20:13
@philmes By default, there can only be one Titan graph instance per jvm. This is important to ensure that the id allocation process does not conflict with other instances. There is some automatic conflict resolution logic in Titan that does not seem to apply in your case. We will try to figure out why.

**Comment by dalaro** [comment] 2014-12-16 18:33
@philmes Are the hostnames of the YARN workers `preference-graph-1`, `preference-graph-2`, ..., `preference-graph-5`?  Are any of the hostnames that connected to the graph prefixes of any other?

**Comment by philmes** [comment] 2014-12-16 18:40
@dalaro correct - three nodes run Cassandra and Yarn and have hostnames `preference-graph-{1/2/3}`. The other two nodes just run Yarn and have hostnames `preference-graph-worker-{1/2}`

**Comment by dalaro** [comment] 2014-12-16 19:29
If none of the hostnames touching the graph are prefixes of any other, then I'm still puzzled.  I wonder if there's some YARN classloader behavior I don't know about.

Is there any pattern to the final token after the `-` in the exceptions?  The first digit in the token will be part of the hostname going from the hostnames in your last reply, but the subsequent numbers (and maybe letters if the counter gets high enough) should be taken from a static atomic long stored and incremented in GraphDatabaseConfiguration.

**Comment by philmes** [comment] 2014-12-16 20:02
I've got some free time tomorrow, so I'll try and reproduce with a debugger attached to some of the workers.

**Comment by dalaro** [comment] 2015-02-17 18:57
Closing this due to inactivity and lack of steps to reproduce.  If someone comes across this with steps to reproduce the problem, please open new or reopen.

**Closed as completed by dalaro** 2015-02-17 18:57 UTC
