### ISSUE TITLE
Delete Operations Fails Due To Negative Timestamps On HBase 0.96

### ISSUE THREAD

**Issue by ghost** [thinkaurelius/titan#577] opened 2014-02-01 10:33 UTC
When running Titan on HBase 0.96 in the Hortonworks sandbox, specified after #526 - it seems like Titan-HBase serves the HBase API Delete call with negative valued timestamps. According to the HBase documentations these cannot have a negative value, and closer inspection showed that was truly the case.

The row in question can be found in `HBaseStoreManager.java` on line 468, and can be temporary solved by setting the timestamp to an absolute value:

```
commands.setSecond(new Delete(key.as(StaticBuffer.ARRAY_FACTORY), Math.abs(delTimestamp)));
```

While having some kind of similar problems in the start when I did the initial changes in #526, I've been running it stable for a month before this. It now seems like something have changed in the Hortonworks repositories, making this persistent on everything.

If running with Rexster, this may be symptomatic by that delete operations fails with script errors.

**Comment by ghost** [comment] 2014-02-03 09:50
I've run this in a testbed a couple of days, and it seems to work quite well. According to the docs this is how I've currently changed the code:

```
Delete(byte[] row, long timestamp)
Create a Delete operation for the specified row and timestamp.
```

Not entirely sure how this will work out in the long run if the timestamp is invalid.

**Comment by dalaro** [comment] 2014-02-04 23:26
Thanks for the report.  I assume this is on titan05 because HBaseStoreManager.java is only 442 lines long in 0.4.2.  Is that correct, and if so, what commit hash are you working from?

As I write this, titan05 HEAD is 837d05077f634cfea64495f0ae1d83f01d715a57.  `delTimestamp` is assigned from `System.currentTimeMillis()` in `mutateMany` and then passed into `convertToCommands` where it is used on the line you quoted.  How can this go negative?  I don't see it.

**Comment by ghost** [comment] 2014-02-05 10:19
I were running it on 26aad45 and with HBase 0.96, but did a pull of the latest HEAD before running it again as well. I've seen the errors periodically previously before they became persistent.

**Comment by dalaro** [comment] 2014-02-06 17:12
I have a few questions then...

I don't want to assume, so I have to ask: are the system clocks set correctly?

I just noticed that your patch casts long timestamps to ints before passing them to the Delete constructor.  Why?  This conversion won't rollover at millisecond resolution until 2038, but it could cause immediate problems if we switch to microsecond timestamps as considered in #483 and #472.  And I don't see why it's necessary.

Putting that aside, I still don't think we're any closer to understanding the root cause.  The HBase adapter in both 0.4.2 and the commit you linked is hardcoded to use currentTimeMillis() for write command timestamps, and a narrowing conversion to int still shouldn't cause them to rollover, assuming the system clocks are accurate.

I would rather add a sanity check on timestamps that logs warnings or throws an exception when they are insane (e.g. negative) than silently Math.abs'ing them and hoping it all works out.

**Comment by ghost** [comment] 2014-02-06 17:31
It all runs in a sandbox, setup with NTP. So yes.

Re the int casting, I actually don't remember why I set it. I follow your lead on this one.

I would guess an exception is probably a better way to go. I haven't had more time to follow up on this issue, but I'll get back to you when I have.

**Comment by dalaro** [comment] 2014-05-02 18:32
Closing this since I've been unable to reproduce it.

**Closed as completed by dalaro** 2014-05-02 18:32 UTC
