### ISSUE TITLE
Titan 0.5 HadoopGraph.V.count() does not match TitanGraph.V.count()

### ISSUE THREAD

**Issue by yuriythedev** [thinkaurelius/titan#764] opened 2014-09-18 18:15 UTC
This bug is based on my forum post - could you please take a look:

Here is the data and it is based on examples/graph-of-the-gods.id shipped with Titan 0.5:

HadoopGraph:  g.V.map():

==>16416        {_id=[16416]}
==>16456        {_id=[16456]}
==>16536        {_id=[16536]}
==>163856648    {_id=[163856648]}
==>327696648    {_id=[327696648]}

g.E.map():

==>163842052    {_id=[163842052], userId=[1], _label=[friend]}
==>491522052    {_id=[491522052], userId=[1], _label=[friend]}
==>327682052    {_id=[327682052], userId=[1], _label=[friend]}
==>655362052    {_id=[655362052], userId=[1], _label=[friend]}
==>491522057    {_id=[491522057], userId=[2], _label=[friend]}
==>163842057    {_id=[163842057], userId=[2], _label=[friend]}
==>327682057    {_id=[327682057], userId=[2], _label=[friend]}
==>655362067    {_id=[655362067], userId=[7], _label=[friend]}
==>327682067    {_id=[327682067], userId=[7], _label=[friend]}
==>163842067    {_id=[163842067], userId=[7], _label=[friend]}
==>491522067    {_id=[491522067], userId=[7], _label=[friend]}
==>819202067    {_id=[819202067], userId=[7], _label=[friend]}
==>983042081    {_id=[983042081], userId=[11], _label=[friend]}
==>819202081    {_id=[819202081], userId=[3], _label=[friend]}
==>491522081    {_id=[491522081], userId=[3], _label=[friend]}
==>...

TitanGraph:

gremlin> g.E.map()
11:45:41 WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
==>{userId=1}
==>{userId=1}
==>{userId=1}
==>{userId=1}
==>{userId=2}
==>{userId=2}
==>{userId=2}
==>{userId=7}
==>{userId=7}
==>{userId=7}
==>{userId=7}
==>{userId=7}
==>{userId=11}
==>{userId=3}
==>{userId=3}
==>{userId=3}
==>{userId=3}

gremlin> g.V
11:48:11 WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
==>v[16416]
==>v[16440]
==>v[16456]
==>v[16536]
==>v[16592]
==>v[16648]
==>v[163856648]
==>v[327696648]
==>v[16824]
==>v[163856824]
==>v[16832]
==>v[16864]
gremlin>

g.V.map is useless with TItanGraph:

gremlin> g.V.map()
11:48:48 WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
==>{}
==>{}
==>{}
==>{}
==>{}
==>{}
==>{}
==>{}
==>{}
==>{}
==>{}
==>{}

The data was inserted by TitanHadoop into Titan backed by HBase cluster.
Note that after the insertion, Hadoop reports that 12 vertices were inserted:

```
com.thinkaurelius.titan.hadoop.formats.util.TitanGraphOutputMapReduce$Counters
        EDGES_ADDED=17
        EDGE_PROPERTIES_ADDED=17
        SUCCESSFUL_TRANSACTIONS=82
        VERTICES_ADDED=12
```

After the insertion, I just create a graph with Titan-Hbase-Input.properties config and do g.V.count()/g.V.map()
Here are the additional files generated by the Hadoop execution:

gremlin> hdfs.head('jobs/job-0/graph-m-00000')
==>{"_id":16416,"_outE":[{"_id":null,"userId":1,"_inV":16864,"_label":"friend"},{"_id":null,"userId":1,"_inV":327696648,"_label":"friend"},{"_id":null,"userId":1,"_inV":16440,"_lab
el":"friend"},{"_id":null,"userId":1,"_inV":16456,"_label":"friend"}]}
==>{"_id":16456,"_outE":[{"_id":null,"userId":2,"_inV":327696648,"_label":"friend"},{"_id":null,"userId":2,"_inV":16832,"_label":"friend"},{"_id":null,"userId":2,"_inV":16416,"_lab
el":"friend"}]}
==>{"_id":16536,"_outE":[{"_id":null,"userId":7,"_inV":16592,"_label":"friend"},{"_id":null,"userId":7,"_inV":16648,"_label":"friend"},{"_id":null,"userId":7,"_inV":163856648,"_lab
el":"friend"},{"_id":null,"userId":7,"_inV":16416,"_label":"friend"},{"_id":null,"userId":7,"_inV":163856824,"_label":"friend"}]}
==>{"_id":163856648,"_outE":[{"_id":null,"userId":11,"_inV":16824,"_label":"friend"}]}
==>{"_id":327696648,"_outE":[{"_id":null,"userId":3,"_inV":16456,"_label":"friend"},{"_id":null,"userId":3,"_inV":163856648,"_label":"friend"},{"_id":null,"userId":3,"_inV":16416,"
_label":"friend"},{"_id":null,"userId":3,"_inV":16824,"_label":"friend"}]}
gremlin>

gremlin> hdfs.head('jobs/job-0/sideeffect-m-00000')
==>163842052    {_id=[163842052], userId=[1], _label=[friend]}
==>491522052    {_id=[491522052], userId=[1], _label=[friend]}
==>327682052    {_id=[327682052], userId=[1], _label=[friend]}
==>655362052    {_id=[655362052], userId=[1], _label=[friend]}
==>491522057    {_id=[491522057], userId=[2], _label=[friend]}
==>163842057    {_id=[163842057], userId=[2], _label=[friend]}
==>327682057    {_id=[327682057], userId=[2], _label=[friend]}
==>655362067    {_id=[655362067], userId=[7], _label=[friend]}
==>327682067    {_id=[327682067], userId=[7], _label=[friend]}
==>163842067    {_id=[163842067], userId=[7], _label=[friend]}
==>491522067    {_id=[491522067], userId=[7], _label=[friend]}
==>819202067    {_id=[819202067], userId=[7], _label=[friend]}
==>983042081    {_id=[983042081], userId=[11], _label=[friend]}
==>819202081    {_id=[819202081], userId=[3], _label=[friend]}
==>491522081    {_id=[491522081], userId=[3], _label=[friend]}
==>655362081    {_id=[655362081], userId=[3], _label=[friend]}
==>983044129    {_id=[983044129], userId=[3], _label=[friend]}
gremlin>

Changing the output format from Graphson to Noop in Titan-Hbase-Input.properties does not really change anything.

Please let me know if you'd like me to get more data to you.

Thanks,
Yuriy
- hide quoted text -

On Thursday, September 4, 2014 8:33:20 PM UTC-7, Matthias wrote:
yes, map would be a good start. THanks!

On Thu, Sep 4, 2014 at 11:30 AM, Yuriy yuriy...@gmail.com wrote:
Thanks Mathias.

I no longer have this data, but I will try to repro this again
What is the best way to print out the contents?
Just use map()? Or is there a better way?

On Wednesday, September 3, 2014 11:54:54 PM UTC-7, Matthias wrote:
That is really bizarre. Since the graph is small, can you try to print out the content for both cases so they can be compared?
Thanks,
Matthias

On Wed, Sep 3, 2014 at 7:20 PM, Yuriy yuriy...@gmail.com wrote:
After loading some tiny test data using TitanHadoop, I ran HadoopGraph.V.count() and TitanGraph.V.count().
These appear to produce different results - any ideas why?

g = HadoopFactory.open('../conf/hadoop/titan-hbase-input.properties')
g.V.count()

---

```
    Shuffle Errors
            BAD_ID=0
            CONNECTION=0
            IO_ERROR=0
            WRONG_LENGTH=0
            WRONG_MAP=0
            WRONG_REDUCE=0
    com.thinkaurelius.titan.hadoop.mapreduce.transform.VerticesMap$Counters
            EDGES_PROCESSED=0
            VERTICES_PROCESSED=5
    com.thinkaurelius.titan.hadoop.mapreduce.util.CountMapReduce$Counters
            VERTICES_COUNTED=5
    File Input Format Counters
            Bytes Read=0
    File Output Format Counters
            Bytes Written=0
```

==>5

g.shutdown()
g = TitanFactory.open("../conf/titan-hbase.properties")
g.V.count()

19:13:02 WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
==>36

The connection properties files are as these where supplied by Titan distro - I just changed HBase (.98) zookeeper connection string in these.
I should also add that I am using your latest and greatest stuff - the Titan package was built from the latest 0.5.1 branch, sync'd Tuesday

Thanks,
Yuriy

**Comment by dalaro** [comment] 2014-11-15 01:17
@yuriythedev I'm really late to this party.  I haven't been able to reproduce this issue.  I tried with the following:
- HBase 0.98.2-hadoop2 (client & server)
- Hadoop 2.2.0 using the default LocalJobRunner
- titan05, currently 0.5.2-SNAPSHOT / commit ee67f0069d971aa8ffa88cf5b7231e7b1a38dd3d.  I recommend against using 0.5.1 to test this specific bug because this scenario is likely to trigger #786.  That's currently fixed on titan05.
- `HadoopFactory.open('conf/hadoop/titan-hbase-output.properties') ; g._` in gremlin.sh to load data into Titan
- Restarted gremlin.sh after loading, then ran `HadoopFactory.open('conf/hadoop/titan-hbase-input.properties') ; g.V().map()` to read vertices from Titan using Hadoop -- this returned all 12, not fewer than 12 as would be expected based on the bug report

**Closed as completed** 2015-03-19 23:35 UTC
Labels: bug
