### ISSUE TITLE
Could not commit transaction due to exception during persistence

### ISSUE THREAD

**Issue by hariharshankar** [thinkaurelius/titan#229] opened 2013-04-19 17:15 UTC
This exception is thrown everytime a transaction is committed to titan, after a script that would write to titan failed once (because of a bug in the script). This exception persists until the titan server is restarted again. 

Exception in thread "main" com.thinkaurelius.titan.core.TitanException: Could not commit transaction due to exception during persistence
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.commit(StandardTitanTx.java:805)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.commit(TitanBlueprintsGraph.java:38)
    at com.tinkerpop.blueprints.TransactionalGraph$commit.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at gov.lanl.egosystem.discovery.utils.BatchTwitter.main(BatchTwitter.groovy:41)
Caused by: com.thinkaurelius.titan.diskstorage.PermanentStorageException: Unknown exception while executing index operation
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.convert(ElasticSearchIndex.java:169)
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.mutate(ElasticSearchIndex.java:301)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.flushInternal(IndexTransaction.java:88)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.commit(IndexTransaction.java:70)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.commit(BackendTransaction.java:67)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.commit(StandardTitanTx.java:798)
    ... 6 more
Caused by: org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: no requests added;
    at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:29)
    at org.elasticsearch.action.bulk.BulkRequest.validate(BulkRequest.java:375)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:55)
    at org.elasticsearch.action.bulk.TransportBulkAction$TransportHandler.messageReceived(TransportBulkAction.java:272)
    at org.elasticsearch.action.bulk.TransportBulkAction$TransportHandler.messageReceived(TransportBulkAction.java:261)
    at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:210)
    at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:111)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:560)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:787)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:560)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:787)
    at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:560)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:555)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)

**Comment by hariharshankar** [comment] 2013-04-19 17:28
Update:
This exception is thrown even after I restarted both elasticsearch and titan servers. I guess the data directories need to be deleted and everything has to start afresh to get around this exception.

**Comment by hariharshankar** [comment] 2013-04-29 23:08
I was able to reproduce this error in a controlled env:

The "name" field is indexed in both elasticsearch and cassandra. 

``` text
gremlin> v = g.V("name", "Rodriguez, Marko").next()
gremlin> v.name
==>Rodriguez, Marko
gremlin> v.name="Marko"
==>Marko
gremlin> g.commit()
4083593 [elasticsearch[Washout][transport_client_worker][T#3]{New I/O worker #54}] WARN  org.elasticsearch.transport.netty  - [Washout] Message not fully read (response) for [32] handler org.elasticsearch.action.TransportActionNodeProxy$1@29ffddb4, error [true], resetting
Could not commit transaction due to exception during persistence
Display stack trace? [yN]
```

**Comment by mbroecheler** [comment] 2013-04-29 23:11
Thanks, this is very useful. I am on it.

On Mon, Apr 29, 2013 at 4:08 PM, hariharshankar notifications@github.comwrote:

> I was able to reproduce this error in a controlled env:
> 
> The "name" field is indexed in both elasticsearch and cassandra.
> 
> gremlin> v = g.V("name", "Rodriguez, Marko").next()
> gremlin> v.name
> ==>Rodriguez, Marko
> gremlin> v.name="Marko"
> ==>Marko
> gremlin> g.commit()
> 4083593 [elasticsearch[Washout][transport_client_worker][T#3]{New I/O worker #54}] WARN  org.elasticsearch.transport.netty  - [Washout] Message not fully read (response) for [32] handler org.elasticsearch.action.TransportActionNodeProxy$1@29ffddb4, error [true], resetting
> Could not commit transaction due to exception during persistence
> Display stack trace? [yN]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/229#issuecomment-17200377
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by okram** [comment] 2013-04-30 16:01
So I have checked this for 2 combinations.
1. JUST CASSANDRA INDEXING (works!)
2. JUST ELASTIC SEARCH INDEXING (does not work!)

In short, you can not update a property on a vertex that has been indexed by ElasticSearch.

**Comment by okram** [comment] 2013-05-02 18:24
This patch has been validated at scale and appears to be working now. Thanks.

**Comment by hariharshankar** [comment] 2013-06-13 21:39
This issue seems to have resurfaced again: 

``` text
gremlin> g = TitanFactory.open("bin/cassandra-es.local")
gremlin> v1 = g.addVertex(null)
==>v[4]
gremlin> v1.addProperty("name", "vertex1")
==>e[Q1T-4-2F0LaTPQAG][4-v[36028797018963978]->vertex1]
gremlin> g.commit()
==>null
gremlin> v = g.v(4)
==>v[4]
gremlin> v.name
==>vertex1
gremlin> v.name = "vertex2"
==>vertex2
gremlin> g.commit()
220589 [elasticsearch[Madelyne Pryor][transport_client_worker][T#7]{New I/O worker #7}] WARN  org.elasticsearch.transport.netty  - [Madelyne Pryor] Message not fully read (response) for [66] handler org.elasticsearch.action.TransportActionNodeProxy$1@69346f6a, error [true], resetting
220591 [main] ERROR com.thinkaurelius.titan.diskstorage.locking.consistentkey.LocalLockMediator  - Local unlock failed: no locks found for KeyColumn [k=0x0-0-0-0-0-0-0-8, c=0x1-138]
220591 [main] WARN  com.thinkaurelius.titan.diskstorage.locking.consistentkey.ConsistentKeyLockTransaction  - Failed to release LockClaim [backer=com.thinkaurelius.titan.diskstorage.locking.consistentkey.ConsistentKeyLockStore@355a8e36, key=0x0-0-0-0-0-0-0-8, col=0x1-138, expectedValue=0x1-118-101-114-116-101-120-177-12-26-197] locally (txn=com.thinkaurelius.titan.diskstorage.locking.consistentkey.ConsistentKeyLockTransaction@4e42b9fd)
Could not commit transaction due to exception during persistence
Display stack trace? [yN]
```

**Comment by dkuppitz** [comment] 2013-06-15 19:52
Same with "normal" edges:

```
gremlin> g = TitanFactory.open('/tmp/bar')
==>titangraph[local:/tmp/bar]
gremlin> t = g.makeType().name("type").dataType(Integer.class).unique(OUT).indexed(Edge.class).makePropertyKey()
==>v[36028797018963978]
gremlin> g.makeType().name("friend").primaryKey(t).makeEdgeLabel()
==>v[36028797018963990]
gremlin> g.commit()
==>null
gremlin> v1 = g.addVertex(null)
==>v[4]
gremlin> v2 = g.addVertex(null)
==>v[8]
gremlin> v1.addEdge("friend", v2).setProperty("type", 0)
==>null
gremlin> g.commit()
==>null
gremlin> v1.outE("friend").inV().filter{ it == v2 }.back(2).sideEffect{ it.setProperty("type", 1) }
==>e[l-4-2F0LaTPQAS][4-friend->8]
gremlin> g.commit()
Could not commit transaction due to exception during persistence
Display stack trace? [yN]
```

I've tried a lot of things, but didn't find any workaround. It's not even possible to remove (and recreate) the edge.

**Comment by okram** [comment] 2013-06-17 14:47
I just added this test case to Blueprints.
  https://github.com/tinkerpop/blueprints/blob/ef9210734f917e64807dcada95609e2089fe0ef0/blueprints-test/src/main/java/com/tinkerpop/blueprints/KeyIndexableGraphTestSuite.java#L195

I will extend it to include edge properties in a few.

**Comment by dalaro** [comment] 2013-06-17 17:55
I'm confused.

I ran @okram's new KeyIndexableTestSuite method (testUpdateValuesInIndexKeys) using InternalCassandraBlueprintsTest in the Titan 0.3.1 tag and it passed.  I've been unable to locally reproduce @hariharshankar's exception locally by starting a pristine embedded cassandra + local ES instance and running the gremlin commands as listed.  The last commit just returns null as usual.

What am I missing?  I'm guessing from context that @hariharshankar's "name" type was defined earlier with unique(OUT) and an ES index on Vertex.class, but maybe I'm guessing wrong.  I'd like to reproduce the exact configuration and exception occurring in the supported environment.

I can reproduce the exception in @dkuppitz's script, so I'm going to look at that in the meantime.

**Comment by hariharshankar** [comment] 2013-06-17 18:42
Yes, I forgot to add that. This is the type statement:

``` text
g.makeType().name('name').dataType(String.class).indexed(Vertex.class).indexed("search", Vertex.class).unique(Direction.OUT).makePropertyKey();
```

**Comment by dalaro** [comment] 2013-06-17 19:19
Thanks!

I'm running a freshly-unzipped copy of titan-all-0.3.1.zip.  I've tried embedding Cassandra + ES and running both of them as external processes.  Here's my typical Gremlin output in either configuration:

```
gremlin> g = TitanFactory.open("bin/cassandrathrift-es.local")
13/06/17 15:13:38 INFO diskstorage.Backend: Configuring index [search] based on: 
 backend: elasticsearch
hostname: 127.0.0.1
client-only: true

13/06/17 15:13:38 INFO elasticsearch.plugins: [Darkhawk] loaded [], sites []
13/06/17 15:13:38 INFO es.ElasticSearchIndex: Configured remote host: 127.0.0.1 : 9300
==>titangraph[cassandrathrift:127.0.0.1]
gremlin> g.makeType().name('name').dataType(String.class).indexed(Vertex.class).indexed("search", Vertex.class).unique(Direction.OUT).makePropertyKey();
==>v[36028797018963978]
gremlin> v1 = g.addVertex(null)
==>v[4]
gremlin> v1.addProperty("name", "vertex1")
==>e[b-4-2F0LaTPQAG][4-v[36028797018963978]->vertex1]
gremlin> g.commit()
==>null
gremlin> v = g.v(4)
==>v[4]
gremlin> v.name
==>vertex1
gremlin> v.name = "vertex2"
==>vertex2
gremlin> g.commit()
==>null
gremlin>
```

In your first message, you wrote that "This exception is thrown everytime a transaction is committed to titan, after a script that would write to titan failed once (because of a bug in the script)."  Is this what I'm missing?  Do I need to run some deliberately error-producing Gremlin script against Titan to get it into a broken state, then run the Gremlin commands listed above?

Sorry I'm having trouble reproducing the problem.  I appreciate your patience and help.

**Comment by dalaro** [comment] 2013-06-17 19:23
Here are the two configurations that I tried:

```
$ cat cassandrathrift-es.local 
storage.backend=cassandrathrift
storage.hostname=127.0.0.1
storage.index.search.backend=elasticsearch
storage.index.search.hostname=127.0.0.1
storage.index.search.client-only=true

$ cat embeddedcassandra-embeddedes.local 
storage.backend=embeddedcassandra 
storage.index.search.backend=elasticsearch
storage.index.search.directory=/tmp/searchindex
storage.index.search.client-only=false
storage.index.search.local-mode=true
```

**Comment by hariharshankar** [comment] 2013-06-17 19:49
I ran a clean instance of titan/cassandra similar to @dalaro's comments and I am not able to reproduce this error now! I guess there is something wrong with my configurations. I will try to locate the problem. Sorry for the troubles.

**Comment by mbroecheler** [comment] 2013-06-28 20:28
closed until further incidences are found.
Created issue #314 for the discovered (unrelated) issue

**Closed as completed by mbroecheler** 2013-06-28 20:28 UTC
Labels: bug

**Comment by kevinisaac** [comment] 2015-01-15 16:44
I faced this issue now. I can write to the database normally but when I open the graph in the gremlin console like this : `g = TitanFactory.open("/location/to/db")`, I cannot update properties of a vertex until Titan is restarted.
