### ISSUE TITLE
Upgrade to Reflections 0.9.9 to avoid NoSuchMethodError

### ISSUE THREAD

**Issue by BrynCooke** [thinkaurelius/titan#778] opened 2014-10-08 13:55 UTC
Titan 0.5
There was a change method signature for ClasspathHelper.forJavaClassPath between Reflections 0.9.9-RC1 and 0.9.9

Using Titan in a project where this dependency has been upgraded results in:
14:41:40.630 [http-nio-8080-exec-3] ERROR c.t.t.c.u.ReflectiveConfigOptionLoader - Failed to iterate over classpath using Reflections; this usually indicates a broken classpath/classloader 
java.lang.NoSuchMethodError: org.reflections.util.ClasspathHelper.forJavaClassPath()Ljava/util/Set;

**Comment by dalaro** [comment] 2014-10-09 02:30
The last call to `forJavaClassPath(...)` was replaced by a call to `forClassLoader` that passes in an array of `ClassLoader` in 0b2620d9aec9292a4e79f53291dbc50689b7b130.  The related issue is #711.  This is not contained in 0.5.0.  It is in titan05 and will be part of 0.5.1.  The `forClassLoader` method with a vararg `ClassLoader` signature still seems to exist in 0.9.9.  Please reopen if I'm mistaken.

**Comment by BrynCooke** [comment] 2014-10-09 08:26
forClassLoader is there but the return type is different between 0.9.9-RC1 and 0.9.9. Unfortunately this is the same as a completely new method.

Here is the full stack trace when reflections 0.9.9 is on my classpath:

```
java.lang.NoSuchMethodError: org.reflections.util.ClasspathHelper.forJavaClassPath()Ljava/util/Set;
    at com.thinkaurelius.titan.core.util.ReflectiveConfigOptionLoader.loadAllClassesUnsafe(ReflectiveConfigOptionLoader.java:48) [titan-core-0.5.0.jar:na]
    at com.thinkaurelius.titan.core.util.ReflectiveConfigOptionLoader.load(ReflectiveConfigOptionLoader.java:35) [titan-core-0.5.0.jar:na]
    at com.thinkaurelius.titan.core.util.ReflectiveConfigOptionLoader.loadOnce(ReflectiveConfigOptionLoader.java:121) [titan-core-0.5.0.jar:na]
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:91) [titan-core-0.5.0.jar:na]
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:71) [titan-core-0.5.0.jar:na]

```

**Comment by BrynCooke** [comment] 2014-10-09 21:22
Apologies.  I see you are saying this is will be merged into titan05 later

**Comment by dalaro** [comment] 2014-10-09 21:24
@BrynCooke there was a miscommunication.  I don't have any stuff sitting on a feature branch waiting to fix this -- just the commit and issue linked above (and the issue's already closed).  IMO this should remain open.

**Comment by dalaro** [comment] 2014-10-09 22:03
The `forClassLoader` method is pretty small, so I copied it into `ReflectiveConfigOptionLoader` and removed its use of `ClasspathHelper` altogether.

However, this led to another problem.  When Titan is compiled and tested under 0.9.9-RC1 but given 0.9.9 at runtime, the classes involved load and the methods resolve, and the thread of control calls into `Reflections.getTypesAnnotatedWith` as intended, but the 0.9.9 implementation throws an exception seemingly relating to its configuration:

```
17:23:34 ERROR com.thinkaurelius.titan.core.util.ReflectiveConfigOptionLoader  - Failed to iterate over classpath using Reflections; this usually indicates a broken classpath/classloader
org.reflections.ReflectionsException: Scanner SubTypesScanner was not configured
        at org.reflections.Store.get(Store.java:58)
        at org.reflections.Store.get(Store.java:70)
        at org.reflections.Store.getAll(Store.java:97)
        at org.reflections.Reflections.getAllAnnotated(Reflections.java:423)
        at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:384)
        at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:370)
        at com.thinkaurelius.titan.core.util.ReflectiveConfigOptionLoader.loadAllClassesUnsafe(ReflectiveConfigOptionLoader.java:224)
        at com.thinkaurelius.titan.core.util.ReflectiveConfigOptionLoader.load(ReflectiveConfigOptionLoader.java:193)
        at com.thinkaurelius.titan.core.util.ReflectiveConfigOptionLoader.loadAll(ReflectiveConfigOptionLoader.java:86)
        at com.thinkaurelius.titan.core.util.ReflectiveConfigOptionLoader$loadAll.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        ...
```

This is not thrown with 0.9.9-RC1.  Reflections seems to behave differently between these two versions given the same config.

I added a `SubTypesScanner` to the Reflections instance constructed in `loadAll`, and now it seems to work with both 0.9.9-RC1 and 0.9.9.  Titan's still compiling against 0.9.9-RC1, but dropping in 0.9.9 at runtime no longer breaks it.  Though adding `SubTypesScanner` doesn't change the set of 77 classes discovered with Reflections and logged at `DEBUG`, it does seem to make Reflections build more metadata in order to do it:

Without `SubTypesScanner`:

```
17:36:34 INFO  org.reflections.Reflections  - Reflections took 3762 ms to scan 293 urls, producing 141 keys and 8964 values
```

With `SubTypesScanner`:

```
17:39:28 INFO  org.reflections.Reflections  - Reflections took 3967 ms to scan 293 urls, producing 12386 keys and 68672 values
```

**Comment by dalaro** [comment] 2014-10-09 22:08
I think 7e48bafc8c8f575492dfcd1ce969a7717fb3beeb makes Titan work with Reflections 0.9.9.  Sorry for the false start earlier in the thread involving `forClassLoader`'s return type.

BTW, there's an optimization in titan05 (but not 0.5.0) that covers the standard options without resorting to Reflections.  titan05 now (and 0.5.1 when released) shouldn't call Reflections unless third-party ConfigOptions are referenced.

**Closed as completed** 2014-10-09 23:43 UTC

**Comment by BrynCooke** [comment] 2014-10-10 08:09
Just in case you guys ever decide to refactor the discovery mechanism: [ServiceLoader](http://docs.oracle.com/javase/6/docs/api/java/util/ServiceLoader.html) is designed for this problem and developers already know how to use it. Classpath scanning is always painfully slow even with reflections. I have a web app with Titan embedded and a whole bunch of libraries, the existing scan adds 5 seconds to the Titan graph startup time, if I didn't have an SSD it would be tens of seconds.

**Comment by dalaro** [comment] 2014-10-11 04:18
@BrynCooke ServiceLoader is a great suggestion.  I wasn't ready to go that heavyweight at the outset, but it may be worth it to formalize a SPI framework for StoreManager and IndexProvider impls.

Regarding speed: 0.5.1 attempts to avoid classpath scanning when possible.  If only standard Titan opts are in use (no third-party additions), then it should preload a small set of hard-coded mainline Titan classes by name and avoid walking the classpath.  Went from 4 s to 65 ms here.
