### ISSUE TITLE
POM Refactoring for multi modules

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#120] opened 2012-12-13 06:17 UTC
so that each storage backend becomes its own module.

**Comment by devsprint** [comment] 2013-01-02 18:14
it seems that also hadoop support has to be in its own module.

**Comment by okram** [comment] 2013-01-02 18:59
@mbroecheler -- I can do this at anytime. What needs to happen is all branches need to be merged into master as this change will cause merging nightmare afterwards. Once that happens, I need ~1-2 hours to modularize the project with no one forking or touching master.

**Comment by xedin** [comment] 2013-01-05 09:16
This introduced dependency problem in cassadra-1-2-integration branch after merging from master

Running com.thinkaurelius.titan.diskstorage.cassandra.thrift.InternalCassandraThriftMultiWriteKeyColumnValueStoreTest
java.lang.NoClassDefFoundError: org/jboss/netty/logging/InternalLoggerFactory
    at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:328)
    at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:397)
    at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:440)
    at com.thinkaurelius.titan.diskstorage.cassandra.embedded.CassandraDaemonWrapper$CassandraStarter.run(CassandraDaemonWrapper.java:66)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ClassNotFoundException: org.jboss.netty.logging.InternalLoggerFactory
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 10 more
Exception encountered during startup: org/jboss/netty/logging/InternalLoggerFactory

**Comment by mbroecheler** [comment] 2013-01-05 18:25
What is causing this?

On Sat, Jan 5, 2013 at 1:16 AM, Pavel Yaskevich notifications@github.comwrote:

> This introduced dependency problem in cassadra-1-2-integration branch
> after merging from master
> 
> Running
> com.thinkaurelius.titan.diskstorage.cassandra.thrift.InternalCassandraThriftMultiWriteKeyColumnValueStoreTest
> 673java.lang.NoClassDefFoundError:
> org/jboss/netty/logging/InternalLoggerFactory
> 674 at
> org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:328)
> 675 at
> org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:397)
> 676 at
> org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:440)
> 677 at
> com.thinkaurelius.titan.diskstorage.cassandra.embedded.CassandraDaemonWrapper$CassandraStarter.run(CassandraDaemonWrapper.java:66)
> 678 at
> java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
> 679 at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
> 680 at java.util.concurrent.FutureTask.run(FutureTask.java:166)
> 681 at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
> 682 at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
> 683 at java.lang.Thread.run(Thread.java:722)
> 684Caused by: java.lang.ClassNotFoundException:
> org.jboss.netty.logging.InternalLoggerFactory
> 685 at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
> 686 at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
> 687 at java.security.AccessController.doPrivileged(Native Method)
> 688 at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
> 689 at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
> 690 at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
> 691 at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
> 692 ... 10 more
> 693Exception encountered during startup:
> org/jboss/netty/logging/InternalLoggerFactory
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/120#issuecomment-11911960.

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by xedin** [comment] 2013-01-06 01:37
It looks like system can't find this class "org/jboss/netty/logging/InternalLoggerFactory" for Titan-Cassandra package, this happend when I merged change from master.

**Comment by xedin** [comment] 2013-01-06 01:54
I have found the cause of problem, will close as soon as made sure.

**Comment by xedin** [comment] 2013-01-06 02:08
mvn clean test - passed, but there is another problem in master and my branch, when I do mvn clean install or mvn clean package I get this 

[ERROR] Failed to execute goal on project titan-berkeleyje: Could not resolve dependencies for project com.thinkaurelius.titan:titan-berkeleyje:jar:0.3.0-SNAPSHOT: Failure to find com.thinkaurelius.titan:titan-test:jar:0.3.0-SNAPSHOT in http://download.oracle.com/maven was cached in the local repository, resolution will not be reattempted until the update interval of oracleReleases has elapsed or updates are forced -> [Help 1]

**Comment by okram** [comment] 2013-01-06 02:13
When all of these modules build fully, we need to:
1. go through each pom.xml and remove all dependencies not needed.
2. go through each pom.xml and try and push <plugin>s to parent pom.
3. figure out the resource/ requirements in src and test.
4. create a single titan-all that has the Gremlin shells.

**Comment by mbroecheler** [comment] 2013-01-06 10:00
Hey Vadas,

thanks for working this out. Both Marko and I were seeing similar issues to
the one below and had to build each project individually first before the
mvn clean install on the root level would work. Does that work for you as
well? This is another thing we have to figure out.
Cheers,
Matthias

On Sat, Jan 5, 2013 at 6:09 PM, Pavel Yaskevich notifications@github.comwrote:

> mvn clean test - passed, but there is another problem in master and my
> branch, when I do mvn clean install or mvn clean package I get this
> 
> [ERROR] Failed to execute goal on project titan-berkeleyje: Could not
> resolve dependencies for project
> com.thinkaurelius.titan:titan-berkeleyje:jar:0.3.0-SNAPSHOT: Failure to
> find com.thinkaurelius.titan:titan-test:jar:0.3.0-SNAPSHOT in
> http://download.oracle.com/maven was cached in the local repository,
> resolution will not be reattempted until the update interval of
> oracleReleases has elapsed or updates are forced -> [Help 1]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/120#issuecomment-11923187.

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by vadasg** [comment] 2013-01-06 11:17
emailMessage.replace("Vadas","Pavel") probably :)

**Comment by mbroecheler** [comment] 2013-01-06 21:06
Gee, I am sorry - it was late ;-)
Of course I meant Pavel.
Have you tried building individually, Pavel?

On Sun, Jan 6, 2013 at 2:00 AM, Matthias Broecheler me@matthiasb.comwrote:

> Hey Vadas,
> 
> thanks for working this out. Both Marko and I were seeing similar issues
> to the one below and had to build each project individually first before
> the mvn clean install on the root level would work. Does that work for you
> as well? This is another thing we have to figure out.
> Cheers,
> Matthias
> 
> On Sat, Jan 5, 2013 at 6:09 PM, Pavel Yaskevich notifications@github.comwrote:
> 
> > mvn clean test - passed, but there is another problem in master and my
> > branch, when I do mvn clean install or mvn clean package I get this
> > 
> > [ERROR] Failed to execute goal on project titan-berkeleyje: Could not
> > resolve dependencies for project
> > com.thinkaurelius.titan:titan-berkeleyje:jar:0.3.0-SNAPSHOT: Failure to
> > find com.thinkaurelius.titan:titan-test:jar:0.3.0-SNAPSHOT in
> > http://download.oracle.com/maven was cached in the local repository,
> > resolution will not be reattempted until the update interval of
> > oracleReleases has elapsed or updates are forced -> [Help 1]
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/120#issuecomment-11923187.
> 
> ## 
> 
> Matthias Broecheler, PhD
> http://www.matthiasb.com
> E-Mail: me@matthiasb.com

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by xedin** [comment] 2013-01-06 21:29
I did try building them (with mvn clean) one by one and the same error happens with berkleyje, cassandra and hbase modules

http://pastebin.com/iLZV5Yea

I didn't include hbase error there because it's exactly the same as titan-cassandra

**Comment by devsprint** [comment] 2013-01-07 15:23
Guys,

I have checkout the cassandra-1-2-integration branch and I'm not seeing the issues mention above. Try to remove 0.3.0-SNAPSHOT artifacts from your local repo and run mvn clean install in root. This is what I'm doing...

However, in the test.log file below, it seems that there are some issues with the startup of Cassandra Daemon caused by the change of the partitioner strategy... see last 2 lines. Basically the daemon starts but exists because of a Runtime exception.

16216 [pool-1-thread-1] INFO  org.apache.cassandra.service.CacheService  - Scheduling row cache save to each 0 seconds (going to save all keys).
18742 [SSTableBatchOpen:2] INFO  org.apache.cassandra.io.sstable.SSTableReader  - Opening /Users/gabrielciuloaica/projects/titan/titan/titan-cassandra/target/cassandra-tmp/workdir/127.0.0.1/data/system/schema_keyspaces/system-schema_keyspaces-ia-2 (223 bytes)
18743 [SSTableBatchOpen:1] INFO  org.apache.cassandra.io.sstable.SSTableReader  - Opening /Users/gabrielciuloaica/projects/titan/titan/titan-cassandra/target/cassandra-tmp/workdir/127.0.0.1/data/system/schema_keyspaces/system-schema_keyspaces-ia-1 (750 bytes)
18750 [SSTableBatchOpen:2] ERROR org.apache.cassandra.io.sstable.SSTableReader  - Cannot open /Users/gabrielciuloaica/projects/titan/titan/titan-cassandra/target/cassandra-tmp/workdir/127.0.0.1/data/system/schema_keyspaces/system-schema_keyspaces-ia-2; partitioner org.apache.cassandra.dht.RandomPartitioner does not match system partitioner org.apache.cassandra.dht.ByteOrderedPartitioner.  Note that the default partitioner starting with Cassandra 1.2 is Murmur3Partitioner, so you will need to edit that to match your old partitioner if upgrading.
18750 [SSTableBatchOpen:1] ERROR org.apache.cassandra.io.sstable.SSTableReader  - Cannot open /Users/gabrielciuloaica/projects/titan/titan/titan-cassandra/target/cassandra-tmp/workdir/127.0.0.1/data/system/schema_keyspaces/system-schema_keyspaces-ia-1; partitioner org.apache.cassandra.dht.RandomPartitioner does not match system partitioner org.apache.cassandra.dht.ByteOrderedPartitioner.  Note that the default partitioner starting with Cassandra 1.2 is Murmur3Partitioner, so you will need to edit that to match your old partitioner if upgrading.

Mac Os X 10.8.2, JDK 1.6, Maven 3.0.4

**Comment by xedin** [comment] 2013-01-07 18:08
@devsprint I will try removing those, thanks!

@mbroecheler  I wonder why those tests were working before as nothing wipes out data directory after each run, so when you run with different configs in the same data directory it should fail. Probably Cassandra in 1.1.x wasn't enforcing it hard enough... I will try make random vs ordered partitioner test in the separate directories in my branch.

**Comment by xedin** [comment] 2013-01-07 18:13
So it didn't help, I have removed whole ~/.m2 directory to be sure. When I run 'mvn clean package' from root titan directory it fails with the same error

[ERROR] Failed to execute goal on project titan-berkeleyje: Could not resolve dependencies for project com.thinkaurelius.titan:titan-berkeleyje:jar:0.3.0-SNAPSHOT: Could not find artifact com.thinkaurelius.titan:titan-test:jar:0.3.0-SNAPSHOT in oracleReleases (http://download.oracle.com/maven) -> [Help 1]

**Comment by xedin** [comment] 2013-01-07 19:22
Ok I was able to successfully build everything after doing those steps:
- mvn clean 
- rm -rf ~/.m2
- mvn install -pl titan-test -am (installed test and core)
- mvn install

[INFO] Titan: Distributed Graph Database ................. SUCCESS [1.275s]
[INFO] Titan-Core: Core Distributed Graph Database ....... SUCCESS [10:08.797s]
[INFO] Titan-Test: Distributed Graph Database ............ SUCCESS [13.364s]
[INFO] Titan-BerkeleyJE: Distributed Graph Database ...... SUCCESS [11.853s]
[INFO] Titan-Cassandra: Distributed Graph Database ....... SUCCESS [12.633s]
[INFO] Titan-HBase: Distributed Graph Database ........... SUCCESS [13.850s]

**Comment by xedin** [comment] 2013-01-09 19:32
Ok, to keep everybody up-to-date, cassandra-1-2-integration branch now has fixed maven pom files and builds, tests are working for me as well as gremlin/titan commands.

**Comment by xedin** [comment] 2013-01-10 06:10
Fixed the problem and everything is merged into master, closing this issue.

**Closed as completed by xedin** 2013-01-10 06:10 UTC
Labels: enhancement

**Comment by devsprint** [comment] 2013-01-10 07:23
I can confirm that the build is working properly. Thank you.
