### ISSUE TITLE
Cassandra 2.1 CQL3 Support

### ISSUE THREAD

**Issue by CasperWW** [thinkaurelius/titan#1052] opened 2015-04-29 09:36 UTC
Cassandra 2.1 CLQ3 [shows](http://www.datastax.com/dev/blog/cassandra-2-1-now-over-50-faster) 160% and 150% (read and write respectively) performance gain over the deprecated Thrift framework. A huge optimisation with the combination Titan-Cassandra can be made.

**Comment by mbroecheler** [comment] 2015-06-20 02:14
These benchmarks are based on tabular reads. When we did a comparison it turns out that the lack of multi-row query support in thrift led to an overall reduced performance.

**Comment by mbroecheler** [comment] 2015-06-24 18:57
This is essentially a duplicate of #312

**Closed as completed by mbroecheler** 2015-06-24 18:57 UTC
Labels: duplicate

**Comment by briandilley** [comment] 2015-12-16 07:24
So does that mean titan will never run on CQL?

**Comment by countrodrigo** [comment] 2017-01-04 01:36
Does the CQL migration make sense with the latest C* versions (> 3.x) ?
